// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'https://{YOUR_ORG_ID}.gatana.ai/api/v2' | (string & {});
};

export type V2CreateServerRequest = {
  slug: Schema0;
  transportConfig?: Schema1;
  transportConfigType?: Schema60;
  description?: Schema63;
  authorization?: Schema65;
  oauthMetadata?: Schema74;
  oauthClientConfiguration?: Schema97;
  isEnabled?: Schema112;
  timeoutProtocol?: Schema114;
  timeoutTotal?: Schema116;
  resetTimeoutOnProgressNotification?: Schema118;
  isOutputCompressionEnabled?: Schema120;
  isOutputCompressionTransformEnabled?: Schema122;
  outputCompressionThresholdBytes?: Schema124;
  firewallRules?: Schema126;
  visibility?: Schema129;
  id?: Schema130;
  tenantId?: Schema132;
  lastToolRefreshAt?: Schema134;
  createdAt?: Schema136;
  updatedAt?: Schema138;
};

export type HttpStreamingTransportConfig = {
  type: Schema3;
  url: Schema4;
  headers?: Schema5;
};

export type StdioTransportConfig = {
  type: Schema7;
  command: Schema8;
  dockerImage?: Schema9;
  env?: Schema11;
  transport: Schema13;
  httpPort?: Schema14;
  urlPath?: Schema16;
  healthCheck?: Schema18;
  limits?: Schema24;
  requests?: Schema28;
  storage?: StdioTransportStorage;
  tailscale?: StdioTransportTailscale;
};

/**
 * Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
 */
export type StdioTransportStorage = Schema32 | null;

/**
 * Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
 */
export type StdioTransportTailscale = Schema33 | null;

export type SseTransportConfig = {
  type: Schema35;
  url: Schema36;
  headers?: Schema37;
};

export type HostedTransportConfig = {
  type: Schema39;
  runtime: Schema40;
  env?: Schema41;
  limits?: Schema43;
  requests?: Schema45;
  storage?: HostedTransportStorage;
  tailscale?: HostedTransportTailscale;
};

/**
 * Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
 */
export type HostedTransportStorage = Schema47 | null;

/**
 * Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
 */
export type HostedTransportTailscale = Schema48 | null;

export type OpenApiTransportConfig = {
  type: Schema50;
  method: Schema51;
  specUrl?: Schema52;
  spec?: Schema54;
  baseUrl?: Schema56;
  headers?: Schema58;
};

/**
 * Controls how tool refresh is authorized. "server-scoped" means only server-scoped credentials are required, "skip" means refresh is done without authorization, and "any" means any available credentials (server, user, profile) can be used. Defaults to "server-scoped".
 */
export type ToolRefreshCredentialPolicy = Schema72;

export type ServerAuthorization = {
  method: Schema66;
  credentialsScope: Schema67;
  apikeys?: Schema70;
  toolRefreshCredentialPolicy?: ToolRefreshCredentialPolicy;
};

export type ServerOAuthMetadata = {
  resource?: Schema76;
  as?: Schema81;
};

export type ServerOAuthClientConfiguration = {
  clientId?: Schema99;
  clientSecret?: Schema101;
  grantType: Schema103;
  clientAuthMethod: Schema104;
  scopes?: Schema109;
};

export type OAuthGrantType = 'authorization_code' | 'device_code';

export type ServerVisibility = 'private' | 'organization';

export type V2UpdateServerRequest = {
  slug?: Schema141;
  description?: Schema63;
  authorization?: Schema65;
  transportConfig?: Schema145;
  oauthMetadata?: Schema74;
  oauthClientConfiguration?: Schema97;
  isEnabled?: Schema112;
  timeoutProtocol?: Schema114;
  timeoutTotal?: Schema116;
  resetTimeoutOnProgressNotification?: Schema118;
  isOutputCompressionEnabled?: Schema120;
  isOutputCompressionTransformEnabled?: Schema122;
  outputCompressionThresholdBytes?: Schema124;
  firewallRules?: Schema126;
  visibility?: Schema129;
  id?: Schema158;
  tenantId?: Schema160;
  name?: Schema162;
  lastToolRefreshAt?: Schema164;
  createdAt?: Schema166;
  updatedAt?: Schema168;
};

export type V2PatchServerRequest = {
  [key in Schema170]?: Schema171;
};

/**
 * URL-friendly name of the server, unique within the tenant
 */
export type Schema0 = string;

/**
 * Transport configuration used to connect to the server
 */
export type Schema1 = Schema2;

export type Schema2 =
  | HttpStreamingTransportConfig
  | StdioTransportConfig
  | SseTransportConfig
  | HostedTransportConfig
  | OpenApiTransportConfig;

/**
 * Transport type discriminator, always "httpstreaming"
 */
export type Schema3 = 'httpstreaming';

/**
 * URL of the MCP streamable HTTP endpoint
 */
export type Schema4 = string;

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema5 = Schema6;

export type Schema6 = Array<[string, string]>;

/**
 * Transport type discriminator, always "stdio"
 */
export type Schema7 = 'stdio';

/**
 * Command line that starts the MCP server process
 */
export type Schema8 = string;

/**
 * Docker image that the command runs in
 */
export type Schema9 = Schema10;

export type Schema10 = string;

/**
 * Environment variables for the process, as [name, value] pairs
 */
export type Schema11 = Schema12;

export type Schema12 = Array<[string, string]>;

/**
 * Protocol that the launched process speaks
 */
export type Schema13 = 'sse' | 'httpstreaming' | 'stdio';

/**
 * Port that the process listens on when transport is HTTP-based
 */
export type Schema14 = Schema15 | null;

export type Schema15 = number;

/**
 * URL path of the MCP endpoint when transport is HTTP-based
 */
export type Schema16 = Schema17 | null;

export type Schema17 = string;

/**
 * HTTP health check configuration for the process
 */
export type Schema18 = Schema19;

export type Schema19 = {
  /**
   * Whether the health check is active
   */
  enabled: boolean;
  /**
   * URL that the health check polls
   */
  url?: Schema20;
  /**
   * Seconds to wait before the first health check
   */
  delaySeconds: Schema21 | null;
  /**
   * Seconds between health checks
   */
  intervalSeconds: Schema22 | null;
  /**
   * Number of consecutive failures before the process counts as unhealthy
   */
  failureThreshold: Schema23 | null;
};

export type Schema20 = string;

export type Schema21 = number;

export type Schema22 = number;

export type Schema23 = number;

/**
 * Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
 */
export type Schema24 = Schema25 | null;

export type Schema25 = {
  cpu?: Schema26;
  memory?: Schema27;
};

/**
 * CPU limit in Kubernetes quantity format (e.g. "500m" or "1")
 */
export type Schema26 = string;

/**
 * Memory limit in Kubernetes quantity format (e.g. "512Mi" or "1Gi")
 */
export type Schema27 = string;

/**
 * Resources reserved for the process: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
 */
export type Schema28 = Schema29 | null;

export type Schema29 = {
  cpu?: Schema30;
  memory?: Schema31;
};

/**
 * CPU reserved for the deployment, in Kubernetes quantity format (e.g. "250m" or "1"). This is the minimum the deployment is guaranteed when the hardware is busy; when capacity is free it may use more. Reserved capacity counts against the organization total even while the server idles, so keep it at what the server needs, not what it may burst to
 */
export type Schema30 = string;

/**
 * Memory reserved for the deployment, in Kubernetes quantity format (e.g. "384Mi" or "1Gi"). Unlike CPU this is also the hard ceiling: a process that exceeds it is terminated
 */
export type Schema31 = string;

export type Schema32 = {
  /**
   * Whether the server gets a persistent volume
   */
  enabled: boolean;
};

export type Schema33 = {
  /**
   * Whether the server joins the tailnet
   */
  enabled: boolean;
  /**
   * Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
   */
  authKey: string;
  /**
   * Machine name on the tailnet. Defaults to gatana-<server slug>
   */
  hostname?: Schema34 | null;
};

export type Schema34 = string;

/**
 * Transport type discriminator, always "sse"
 */
export type Schema35 = 'sse';

/**
 * URL of the MCP SSE endpoint
 */
export type Schema36 = string;

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema37 = Schema38;

export type Schema38 = Array<[string, string]>;

/**
 * Transport type discriminator, always "hosted"
 */
export type Schema39 = 'hosted';

/**
 * Runtime that executes the hosted tool functions
 */
export type Schema40 = 'node24' | 'python313';

/**
 * Environment variables for the hosted runtime, as [name, value] pairs
 */
export type Schema41 = Schema42;

export type Schema42 = Array<[string, string]>;

/**
 * Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
 */
export type Schema43 = Schema44 | null;

export type Schema44 = {
  cpu?: Schema26;
  memory?: Schema27;
};

/**
 * Resources reserved for the hosted runtime: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
 */
export type Schema45 = Schema46 | null;

export type Schema46 = {
  cpu?: Schema30;
  memory?: Schema31;
};

export type Schema47 = {
  /**
   * Whether the server gets a persistent volume
   */
  enabled: boolean;
};

export type Schema48 = {
  /**
   * Whether the server joins the tailnet
   */
  enabled: boolean;
  /**
   * Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
   */
  authKey: string;
  /**
   * Machine name on the tailnet. Defaults to gatana-<server slug>
   */
  hostname?: Schema49 | null;
};

export type Schema49 = string;

/**
 * Transport type discriminator, always "openapi"
 */
export type Schema50 = 'openapi';

/**
 * How the OpenAPI spec is supplied: from a URL or as inline content
 */
export type Schema51 = 'specUrl' | 'spec';

/**
 * URL to fetch the OpenAPI spec from, used when method is "specUrl"
 */
export type Schema52 = Schema53;

export type Schema53 = string | '';

/**
 * Inline OpenAPI spec content, used when method is "spec"
 */
export type Schema54 = Schema55;

export type Schema55 = string;

/**
 * Base URL for the API requests generated from the spec
 */
export type Schema56 = Schema57;

export type Schema57 = string | '';

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema58 = Schema59;

export type Schema59 = Array<[string, string]>;

/**
 * Transport type to create with a default configuration, used instead of transportConfig
 */
export type Schema60 = Schema61;

export type Schema61 = 'httpstreaming' | 'sse' | 'stdio' | 'hosted' | 'openapi';

export type Schema62 = Schema63;

/**
 * Human-readable description of the server
 */
export type Schema63 = string;

export type Schema64 = Schema65;

/**
 * Authorization configuration for the server
 */
export type Schema65 = ServerAuthorization;

/**
 * Authorization method that the server uses
 */
export type Schema66 = 'none' | 'oauth' | 'oauth-client-credentials' | 'apikey';

/**
 * Whether credentials are shared for the whole server or stored per user
 */
export type Schema67 = Schema68 | Schema69;

export type Schema68 = 'server';

export type Schema69 = 'user';

/**
 * Names of the API keys that the server expects
 */
export type Schema70 = Schema71;

export type Schema71 = Array<string>;

export type Schema72 = 'server-scoped' | 'skip' | 'any';

export type Schema73 = Schema74;

/**
 * Discovered OAuth metadata, or null when not discovered
 */
export type Schema74 = Schema75 | ServerOAuthMetadata;

export type Schema75 = null;

/**
 * Discovered protected resource metadata (RFC 9728)
 */
export type Schema76 = Schema77;

export type Schema77 = {
  /**
   * Resource identifier from the protected resource metadata
   */
  id?: Schema78;
  /**
   * Scopes that the protected resource supports
   */
  availableScopes?: Schema79;
  /**
   * URL where the protected resource metadata was fetched from
   */
  metadataUrl?: Schema80;
};

export type Schema78 = string;

export type Schema79 = Array<string>;

export type Schema80 = string;

/**
 * Discovered authorization server metadata (RFC 8414)
 */
export type Schema81 = Schema82;

export type Schema82 = {
  /**
   * Issuer identifier of the authorization server
   */
  issuer?: Schema83;
  /**
   * URL of the authorization endpoint
   */
  authorizeEndpoint?: Schema84;
  /**
   * URL of the device authorization endpoint
   */
  deviceAuthorizationEndpoint?: Schema85;
  /**
   * URL of the token endpoint
   */
  tokenEndpoint?: Schema86;
  /**
   * Extra query parameters to add to the authorization request
   */
  extraAuthorizationParameters?: Schema87;
  /**
   * URL of the dynamic client registration endpoint
   */
  registrationEndpoint?: Schema88;
  /**
   * Whether the authorization server supports PKCE
   */
  supportsPKCE?: Schema89;
  /**
   * Client authentication methods that the token endpoint supports
   */
  supportedClientAuthMethods?: Schema90;
  /**
   * Whether the authorization server supports dynamic client registration
   */
  supportsDynamicClientRegistration?: Schema91;
  /**
   * Reason why dynamic client registration is not available
   */
  noDynamicClientRegistrationReason?: Schema92;
  /**
   * URL of the authorization server documentation
   */
  serviceDocumentation?: Schema93;
  /**
   * URL where the authorization server metadata was fetched from
   */
  metadataUrl?: Schema94;
  /**
   * Scopes that the authorization server supports
   */
  availableScopes?: Schema95;
};

export type Schema83 = string;

export type Schema84 = string;

export type Schema85 = string;

export type Schema86 = string;

export type Schema87 = string;

export type Schema88 = string;

export type Schema89 = boolean;

export type Schema90 = Array<string>;

export type Schema91 = boolean;

export type Schema92 = string | null;

export type Schema93 = string;

export type Schema94 = string;

export type Schema95 = Array<string>;

export type Schema96 = Schema97;

/**
 * OAuth client configuration, or null when not configured
 */
export type Schema97 = Schema98 | ServerOAuthClientConfiguration;

export type Schema98 = null;

/**
 * OAuth client ID
 */
export type Schema99 = Schema100;

export type Schema100 = string;

/**
 * OAuth client secret
 */
export type Schema101 = Schema102;

export type Schema102 = string;

/**
 * OAuth grant type used to obtain tokens
 */
export type Schema103 = OAuthGrantType;

/**
 * Client authentication method used at the token endpoint
 */
export type Schema104 = Schema105 | Schema106 | Schema107 | Schema108;

export type Schema105 = 'client_secret_basic';

export type Schema106 = 'client_secret_post';

export type Schema107 = 'none';

export type Schema108 = string;

/**
 * Space-separated OAuth scopes to request
 */
export type Schema109 = Schema110;

export type Schema110 = string;

export type Schema111 = Schema112;

/**
 * Whether the server is enabled
 */
export type Schema112 = boolean;

export type Schema113 = Schema114;

/**
 * Timeout in seconds for a single protocol request to the server
 */
export type Schema114 = number;

export type Schema115 = Schema116;

/**
 * Total timeout in seconds for a tool call, including progress notifications
 */
export type Schema116 = number;

export type Schema117 = Schema118;

/**
 * Whether a progress notification resets the protocol timeout
 */
export type Schema118 = boolean;

export type Schema119 = Schema120;

/**
 * Whether large tool outputs are compressed before they are returned to the client
 */
export type Schema120 = boolean;

export type Schema121 = Schema122;

/**
 * Whether the compression transform step is applied to tool outputs
 */
export type Schema122 = boolean;

export type Schema123 = Schema124;

/**
 * Minimum output size in bytes before compression is applied
 */
export type Schema124 = number;

export type Schema125 = Schema126;

/**
 * Firewall rules evaluated against tool calls to the server
 */
export type Schema126 = Array<Schema127>;

export type Schema127 = {
  /**
   * CEL representing the condition
   */
  condition: string;
  /**
   * Action to take when the condition matches
   */
  action: 'deny' | 'modify' | 'log';
};

export type Schema128 = Schema129;

/**
 * Who can see the server: only members or the whole organization
 */
export type Schema129 = ServerVisibility;

/**
 * Read-only; accepted and ignored
 */
export type Schema130 = Schema131;

export type Schema131 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema132 = Schema133;

export type Schema133 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema134 = Schema135;

export type Schema135 = string | null;

/**
 * Read-only; accepted and ignored
 */
export type Schema136 = Schema137;

export type Schema137 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema138 = Schema139;

export type Schema139 = string;

export type Schema140 = string;

/**
 * URL-friendly name of the server, unique within the tenant
 */
export type Schema141 = Schema142;

export type Schema142 = string;

export type Schema143 = Schema63;

export type Schema144 = Schema65;

/**
 * Transport configuration used to connect to the server
 */
export type Schema145 =
  | HttpStreamingTransportConfig
  | StdioTransportConfig
  | SseTransportConfig
  | Schema146
  | HostedTransportConfig
  | OpenApiTransportConfig;

export type Schema146 = {
  /**
   * Transport type discriminator, always "self"
   */
  type: 'self';
  /**
   * ID of the built-in server implementation
   */
  id: string;
};

export type Schema147 = Schema74;

export type Schema148 = Schema97;

export type Schema149 = Schema112;

export type Schema150 = Schema114;

export type Schema151 = Schema116;

export type Schema152 = Schema118;

export type Schema153 = Schema120;

export type Schema154 = Schema122;

export type Schema155 = Schema124;

export type Schema156 = Schema126;

export type Schema157 = Schema129;

/**
 * Read-only; accepted and ignored
 */
export type Schema158 = Schema159;

export type Schema159 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema160 = Schema161;

export type Schema161 = string;

/**
 * Deprecated; accepted and ignored
 */
export type Schema162 = Schema163;

export type Schema163 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema164 = Schema165;

export type Schema165 = string | null;

/**
 * Read-only; accepted and ignored
 */
export type Schema166 = Schema167;

export type Schema167 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema168 = Schema169;

export type Schema169 = string;

export type Schema170 = string;

export type Schema171 = unknown;

export type Schema172 = string;

export type V2ListServersResponse = {
  servers: Schema173;
};

export type V2ServerDto = Server;

export type Server = {
  id: Schema174;
  slug: Schema175;
  tenantId: Schema176;
  description: Schema177;
  authorization: Schema178;
  transportConfig: Schema186;
  oauthClientConfiguration: Schema245;
  oauthMetadata: Schema259;
  visibility: Schema281;
  isEnabled: Schema282;
  lastToolRefreshAt: Schema283;
  timeoutProtocol: Schema285;
  timeoutTotal: Schema286;
  resetTimeoutOnProgressNotification: Schema287;
  isOutputCompressionEnabled: Schema288;
  isOutputCompressionTransformEnabled: Schema289;
  outputCompressionThresholdBytes: Schema290;
  firewallRules: Schema291;
  createdAt: Schema293;
  updatedAt: Schema294;
};

export type CredentialDtoV2 = {
  id: Schema296;
  tenantId: Schema297;
  scope: Schema298;
  userId: Schema299;
  profileId: Schema301;
  lastUsedAt: Schema303;
  authorizedAt: Schema305;
  type: Schema306;
  createdAt: Schema307;
  updatedAt: Schema308;
  serverSlug: Schema309;
  userEmail: Schema310;
  userName: Schema312;
  profileName: Schema314;
};

export type ServerCredentialsCredential =
  | ({
      type: 'apikey';
    } & ServerCredentialsApiKeys)
  | ({
      type: 'oauth';
    } & ServerCredentialsOauthTokens)
  | ({
      type: 'oauth-client-credentials';
    } & ServerCredentialsOauthClientCredentials);

export type ServerCredentialsApiKeys = {
  type: Schema316;
  apikeys: Schema317;
};

export type ServerCredentialsOauthTokens = {
  type: Schema319;
  tokenSet: Schema320;
};

export type ServerCredentialsOauthClientCredentials = {
  type: Schema329;
  clientConfig?: ServerOAuthClientConfigurationClientCredentials;
  tokenSet?: Schema331;
};

/**
 * Client configuration for OAuth client credentials
 */
export type ServerOAuthClientConfigurationClientCredentials = Schema330;

export type CredentialRefreshResponse = {
  id: Schema332;
  accessTokenExpiresAt: Schema333;
};

export type PaginatedCredentialAuditLog = {
  pagination: Schema335;
  data: Schema342;
};

export type CredentialAuditLog = {
  tenantId: Schema343;
  id: Schema344;
  credentialId: Schema345;
  userId: Schema346;
  eventName: Schema348;
  details: Schema349;
  createdAt: Schema352;
  updatedAt: Schema353;
};

export type Schema173 = Array<Server>;

/**
 * Unique ID of the server
 */
export type Schema174 = string;

/**
 * URL-friendly name of the server, unique within the tenant
 */
export type Schema175 = string;

/**
 * ID of the tenant that owns the server
 */
export type Schema176 = string;

/**
 * Human-readable description of the server
 */
export type Schema177 = string;

/**
 * Authorization configuration for the server
 */
export type Schema178 = ServerAuthorizationOutput;

/**
 * Authorization method that the server uses
 */
export type Schema179 = 'none' | 'oauth' | 'oauth-client-credentials' | 'apikey';

/**
 * Whether credentials are shared for the whole server or stored per user
 */
export type Schema180 = Schema181 | Schema182;

export type Schema181 = 'server';

export type Schema182 = 'user';

/**
 * Names of the API keys that the server expects
 */
export type Schema183 = Schema184;

export type Schema184 = Array<string>;

export type Schema185 = 'server-scoped' | 'skip' | 'any';

/**
 * Transport configuration used to connect to the server
 */
export type Schema186 =
  | HttpStreamingTransportConfigOutput
  | StdioTransportConfigOutput
  | SseTransportConfigOutput
  | Schema223
  | HostedTransportConfigOutput
  | OpenApiTransportConfigOutput;

/**
 * Transport type discriminator, always "httpstreaming"
 */
export type Schema187 = 'httpstreaming';

/**
 * URL of the MCP streamable HTTP endpoint
 */
export type Schema188 = string;

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema189 = Schema190;

export type Schema190 = Array<[string, string]>;

/**
 * Transport type discriminator, always "stdio"
 */
export type Schema191 = 'stdio';

/**
 * Command line that starts the MCP server process
 */
export type Schema192 = string;

/**
 * Docker image that the command runs in
 */
export type Schema193 = Schema194;

export type Schema194 = string;

/**
 * Environment variables for the process, as [name, value] pairs
 */
export type Schema195 = Schema196;

export type Schema196 = Array<[string, string]>;

/**
 * Protocol that the launched process speaks
 */
export type Schema197 = 'sse' | 'httpstreaming' | 'stdio';

/**
 * Port that the process listens on when transport is HTTP-based
 */
export type Schema198 = Schema199 | null;

export type Schema199 = number;

/**
 * URL path of the MCP endpoint when transport is HTTP-based
 */
export type Schema200 = Schema201 | null;

export type Schema201 = string;

/**
 * HTTP health check configuration for the process
 */
export type Schema202 = Schema203;

export type Schema203 = {
  /**
   * Whether the health check is active
   */
  enabled: boolean;
  /**
   * URL that the health check polls
   */
  url: Schema204;
  /**
   * Seconds to wait before the first health check
   */
  delaySeconds: Schema205 | null;
  /**
   * Seconds between health checks
   */
  intervalSeconds: Schema206 | null;
  /**
   * Number of consecutive failures before the process counts as unhealthy
   */
  failureThreshold: Schema207 | null;
};

export type Schema204 = string;

export type Schema205 = number;

export type Schema206 = number;

export type Schema207 = number;

/**
 * Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
 */
export type Schema208 = Schema209 | null;

export type Schema209 = {
  cpu?: Schema210;
  memory?: Schema211;
};

/**
 * CPU limit in Kubernetes quantity format (e.g. "500m" or "1")
 */
export type Schema210 = string;

/**
 * Memory limit in Kubernetes quantity format (e.g. "512Mi" or "1Gi")
 */
export type Schema211 = string;

/**
 * Resources reserved for the process: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
 */
export type Schema212 = Schema213 | null;

export type Schema213 = {
  cpu?: Schema214;
  memory?: Schema215;
};

/**
 * CPU reserved for the deployment, in Kubernetes quantity format (e.g. "250m" or "1"). This is the minimum the deployment is guaranteed when the hardware is busy; when capacity is free it may use more. Reserved capacity counts against the organization total even while the server idles, so keep it at what the server needs, not what it may burst to
 */
export type Schema214 = string;

/**
 * Memory reserved for the deployment, in Kubernetes quantity format (e.g. "384Mi" or "1Gi"). Unlike CPU this is also the hard ceiling: a process that exceeds it is terminated
 */
export type Schema215 = string;

export type Schema216 = {
  /**
   * Whether the server gets a persistent volume
   */
  enabled: boolean;
};

export type Schema217 = {
  /**
   * Whether the server joins the tailnet
   */
  enabled: boolean;
  /**
   * Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
   */
  authKey: string;
  /**
   * Machine name on the tailnet. Defaults to gatana-<server slug>
   */
  hostname?: Schema218 | null;
};

export type Schema218 = string;

/**
 * Transport type discriminator, always "sse"
 */
export type Schema219 = 'sse';

/**
 * URL of the MCP SSE endpoint
 */
export type Schema220 = string;

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema221 = Schema222;

export type Schema222 = Array<[string, string]>;

export type Schema223 = {
  /**
   * Transport type discriminator, always "self"
   */
  type: 'self';
  /**
   * ID of the built-in server implementation
   */
  id: string;
};

/**
 * Transport type discriminator, always "hosted"
 */
export type Schema224 = 'hosted';

/**
 * Runtime that executes the hosted tool functions
 */
export type Schema225 = 'node24' | 'python313';

/**
 * Environment variables for the hosted runtime, as [name, value] pairs
 */
export type Schema226 = Schema227;

export type Schema227 = Array<[string, string]>;

/**
 * Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
 */
export type Schema228 = Schema229 | null;

export type Schema229 = {
  cpu?: Schema210;
  memory?: Schema211;
};

/**
 * Resources reserved for the hosted runtime: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
 */
export type Schema230 = Schema231 | null;

export type Schema231 = {
  cpu?: Schema214;
  memory?: Schema215;
};

export type Schema232 = {
  /**
   * Whether the server gets a persistent volume
   */
  enabled: boolean;
};

export type Schema233 = {
  /**
   * Whether the server joins the tailnet
   */
  enabled: boolean;
  /**
   * Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
   */
  authKey: string;
  /**
   * Machine name on the tailnet. Defaults to gatana-<server slug>
   */
  hostname?: Schema234 | null;
};

export type Schema234 = string;

/**
 * Transport type discriminator, always "openapi"
 */
export type Schema235 = 'openapi';

/**
 * How the OpenAPI spec is supplied: from a URL or as inline content
 */
export type Schema236 = 'specUrl' | 'spec';

/**
 * URL to fetch the OpenAPI spec from, used when method is "specUrl"
 */
export type Schema237 = Schema238;

export type Schema238 = string | '';

/**
 * Inline OpenAPI spec content, used when method is "spec"
 */
export type Schema239 = Schema240;

export type Schema240 = string;

/**
 * Base URL for the API requests generated from the spec
 */
export type Schema241 = Schema242;

export type Schema242 = string | '';

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema243 = Schema244;

export type Schema244 = Array<[string, string]>;

/**
 * OAuth client configuration, or null when not configured
 */
export type Schema245 = Schema246 | ServerOAuthClientConfigurationOutput;

export type Schema246 = null;

/**
 * OAuth client ID
 */
export type Schema247 = Schema248;

export type Schema248 = string;

/**
 * OAuth client secret
 */
export type Schema249 = Schema250;

export type Schema250 = string;

/**
 * OAuth grant type used to obtain tokens
 */
export type Schema251 = OAuthGrantType;

/**
 * Client authentication method used at the token endpoint
 */
export type Schema252 = Schema253 | Schema254 | Schema255 | Schema256;

export type Schema253 = 'client_secret_basic';

export type Schema254 = 'client_secret_post';

export type Schema255 = 'none';

export type Schema256 = string;

/**
 * Space-separated OAuth scopes to request
 */
export type Schema257 = Schema258;

export type Schema258 = string;

/**
 * Discovered OAuth metadata, or null when not discovered
 */
export type Schema259 = Schema260 | ServerOAuthMetadataOutput;

export type Schema260 = null;

/**
 * Discovered protected resource metadata (RFC 9728)
 */
export type Schema261 = Schema262;

export type Schema262 = {
  /**
   * Resource identifier from the protected resource metadata
   */
  id: Schema263;
  /**
   * Scopes that the protected resource supports
   */
  availableScopes: Schema264;
  /**
   * URL where the protected resource metadata was fetched from
   */
  metadataUrl: Schema265;
};

export type Schema263 = string;

export type Schema264 = Array<string>;

export type Schema265 = string;

/**
 * Discovered authorization server metadata (RFC 8414)
 */
export type Schema266 = Schema267;

export type Schema267 = {
  /**
   * Issuer identifier of the authorization server
   */
  issuer: Schema268;
  /**
   * URL of the authorization endpoint
   */
  authorizeEndpoint: Schema269;
  /**
   * URL of the device authorization endpoint
   */
  deviceAuthorizationEndpoint: Schema270;
  /**
   * URL of the token endpoint
   */
  tokenEndpoint: Schema271;
  /**
   * Extra query parameters to add to the authorization request
   */
  extraAuthorizationParameters: Schema272;
  /**
   * URL of the dynamic client registration endpoint
   */
  registrationEndpoint?: Schema273;
  /**
   * Whether the authorization server supports PKCE
   */
  supportsPKCE: Schema274;
  /**
   * Client authentication methods that the token endpoint supports
   */
  supportedClientAuthMethods: Schema275;
  /**
   * Whether the authorization server supports dynamic client registration
   */
  supportsDynamicClientRegistration: Schema276;
  /**
   * Reason why dynamic client registration is not available
   */
  noDynamicClientRegistrationReason?: Schema277;
  /**
   * URL of the authorization server documentation
   */
  serviceDocumentation: Schema278;
  /**
   * URL where the authorization server metadata was fetched from
   */
  metadataUrl: Schema279;
  /**
   * Scopes that the authorization server supports
   */
  availableScopes: Schema280;
};

export type Schema268 = string;

export type Schema269 = string;

export type Schema270 = string;

export type Schema271 = string;

export type Schema272 = string;

export type Schema273 = string;

export type Schema274 = boolean;

export type Schema275 = Array<string>;

export type Schema276 = boolean;

export type Schema277 = string | null;

export type Schema278 = string;

export type Schema279 = string;

export type Schema280 = Array<string>;

/**
 * Who can see the server: only members or the whole organization
 */
export type Schema281 = ServerVisibility;

/**
 * Whether the server is enabled
 */
export type Schema282 = boolean;

/**
 * Time of the last tool refresh, or null if tools were never refreshed
 */
export type Schema283 = Schema284 | null;

export type Schema284 = string;

/**
 * Timeout in seconds for a single protocol request to the server
 */
export type Schema285 = number;

/**
 * Total timeout in seconds for a tool call, including progress notifications
 */
export type Schema286 = number;

/**
 * Whether a progress notification resets the protocol timeout
 */
export type Schema287 = boolean;

/**
 * Whether large tool outputs are compressed before they are returned to the client
 */
export type Schema288 = boolean;

/**
 * Whether the compression transform step is applied to tool outputs
 */
export type Schema289 = boolean;

/**
 * Minimum output size in bytes before compression is applied
 */
export type Schema290 = number;

/**
 * Firewall rules evaluated against tool calls to the server
 */
export type Schema291 = Array<Schema292>;

export type Schema292 = {
  /**
   * CEL representing the condition
   */
  condition: string;
  /**
   * Action to take when the condition matches
   */
  action: 'deny' | 'modify' | 'log';
};

/**
 * Time when the server was created
 */
export type Schema293 = string;

/**
 * Time when the server was last updated
 */
export type Schema294 = string;

export type Schema295 = {
  /**
   * Credentials the caller can read, without secret values
   */
  credentials: Array<CredentialDtoV2>;
};

/**
 * Unique ID of the credential record
 */
export type Schema296 = string;

/**
 * ID of the tenant that owns the credential
 */
export type Schema297 = string;

/**
 * Scope that the credential applies to: server, user, or profile
 */
export type Schema298 = 'server' | 'user' | 'profile';

/**
 * ID of the owning user, or null
 */
export type Schema299 = Schema300 | null;

export type Schema300 = string;

/**
 * ID of the owning profile when scope is "profile", otherwise null
 */
export type Schema301 = Schema302 | null;

export type Schema302 = string;

/**
 * Time when the credential was last used, or null if never used
 */
export type Schema303 = Schema304 | null;

export type Schema304 = string;

/**
 * Time when the credential was authorized
 */
export type Schema305 = string;

/**
 * Authorization method that the credential was created with
 */
export type Schema306 = 'oauth' | 'apikey' | 'oauth-client-credentials';

/**
 * Time when the credential record was created
 */
export type Schema307 = string;

/**
 * Time when the credential record was last updated
 */
export type Schema308 = string;

/**
 * Slug of the server that the credential authorizes access to
 */
export type Schema309 = string;

/**
 * Email address of the owning user, or null
 */
export type Schema310 = Schema311 | null;

export type Schema311 = string;

/**
 * Display name of the owning user, or null
 */
export type Schema312 = Schema313 | null;

export type Schema313 = string;

/**
 * Name of the owning profile, or null
 */
export type Schema314 = Schema315 | null;

export type Schema315 = string;

/**
 * Credential type discriminator, always "apikey"
 */
export type Schema316 = 'apikey';

/**
 * API keys as [name, value] pairs
 */
export type Schema317 = Array<Schema318>;

export type Schema318 = [string, string];

/**
 * Credential type discriminator, always "oauth"
 */
export type Schema319 = 'oauth';

/**
 * OAuth tokens obtained from the authorization flow
 */
export type Schema320 = Schema328;

/**
 * OAuth access token
 */
export type Schema321 = string;

/**
 * Expiry time of the access token, as a Unix epoch timestamp
 */
export type Schema322 = Schema323;

export type Schema323 = number;

/**
 * OpenID Connect ID token, if the authorization server issued one
 */
export type Schema324 = Schema325;

export type Schema325 = string;

/**
 * OAuth refresh token, if the authorization server issued one
 */
export type Schema326 = Schema327;

export type Schema327 = string;

export type Schema328 = {
  accessToken: Schema321;
  accessTokenExpiresAt?: Schema322;
  idToken?: Schema324;
  refreshToken?: Schema326;
};

/**
 * Credential type discriminator, always "oauth-client-credentials"
 */
export type Schema329 = 'oauth-client-credentials';

export type Schema330 = {
  clientId: Schema247;
  clientSecret: Schema249;
  clientAuthMethod: Schema252;
  scopes: Schema257;
};

/**
 * Cached tokenset for client credentials
 */
export type Schema331 = Schema328;

/**
 * ID of the refreshed credential
 */
export type Schema332 = string;

/**
 * Expiry time of the refreshed access token, as a Unix epoch timestamp, or null if unknown
 */
export type Schema333 = Schema334 | null;

export type Schema334 = number;

/**
 * Pagination metadata
 */
export type Schema335 = {
  page: Schema336;
  limit: Schema337;
  total: Schema338;
  totalPages: Schema339;
  hasNext: Schema340;
  hasPrev: Schema341;
};

/**
 * Current page number
 */
export type Schema336 = number;

/**
 * Maximum number of items per page
 */
export type Schema337 = number;

/**
 * Total number of items across all pages
 */
export type Schema338 = number;

/**
 * Total number of pages
 */
export type Schema339 = number;

/**
 * Whether a next page exists
 */
export type Schema340 = boolean;

/**
 * Whether a previous page exists
 */
export type Schema341 = boolean;

/**
 * Items on the current page
 */
export type Schema342 = Array<CredentialAuditLog>;

/**
 * ID of the tenant that owns the entry
 */
export type Schema343 = string;

/**
 * Unique ID of the audit log entry
 */
export type Schema344 = string;

/**
 * ID of the credential that the entry belongs to
 */
export type Schema345 = string;

/**
 * ID of the user who performed the action, or null
 */
export type Schema346 = Schema347 | null;

export type Schema347 = string;

/**
 * Name of the audited event (e.g. "create", "update", "delete")
 */
export type Schema348 = string;

/**
 * Event-specific details; update events include a diff of the change
 */
export type Schema349 = {
  [key in Schema350]?: Schema351;
};

export type Schema350 = string;

export type Schema351 = unknown;

/**
 * Time when the entry was created
 */
export type Schema352 = string;

/**
 * Time when the entry was last updated
 */
export type Schema353 = string;

/**
 * Controls how tool refresh is authorized. "server-scoped" means only server-scoped credentials are required, "skip" means refresh is done without authorization, and "any" means any available credentials (server, user, profile) can be used. Defaults to "server-scoped".
 */
export type ToolRefreshCredentialPolicyOutput = Schema185;

export type ServerAuthorizationOutput = {
  method: Schema179;
  credentialsScope: Schema180;
  apikeys?: Schema183;
  toolRefreshCredentialPolicy: ToolRefreshCredentialPolicyOutput;
};

export type HttpStreamingTransportConfigOutput = {
  type: Schema187;
  url: Schema188;
  headers?: Schema189;
};

export type StdioTransportConfigOutput = {
  type: Schema191;
  command: Schema192;
  dockerImage?: Schema193;
  env?: Schema195;
  transport: Schema197;
  httpPort?: Schema198;
  urlPath?: Schema200;
  healthCheck?: Schema202;
  limits?: Schema208;
  requests?: Schema212;
  storage?: StdioTransportStorageOutput;
  tailscale?: StdioTransportTailscaleOutput;
};

/**
 * Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
 */
export type StdioTransportStorageOutput = Schema216 | null;

/**
 * Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
 */
export type StdioTransportTailscaleOutput = Schema217 | null;

export type SseTransportConfigOutput = {
  type: Schema219;
  url: Schema220;
  headers?: Schema221;
};

export type HostedTransportConfigOutput = {
  type: Schema224;
  runtime: Schema225;
  env?: Schema226;
  limits?: Schema228;
  requests?: Schema230;
  storage?: HostedTransportStorageOutput;
  tailscale?: HostedTransportTailscaleOutput;
};

/**
 * Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
 */
export type HostedTransportStorageOutput = Schema232 | null;

/**
 * Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
 */
export type HostedTransportTailscaleOutput = Schema233 | null;

export type OpenApiTransportConfigOutput = {
  type: Schema235;
  method: Schema236;
  specUrl: Schema237;
  spec: Schema239;
  baseUrl: Schema241;
  headers?: Schema243;
};

export type ServerOAuthClientConfigurationOutput = {
  clientId: Schema247;
  clientSecret: Schema249;
  grantType: Schema251;
  clientAuthMethod: Schema252;
  scopes: Schema257;
};

export type ServerOAuthMetadataOutput = {
  resource?: Schema261;
  as?: Schema266;
};

export type ListServersV2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: '/servers';
};

export type ListServersV2Responses = {
  /**
   * Successful response
   */
  200: V2ListServersResponse;
};

export type ListServersV2Response = ListServersV2Responses[keyof ListServersV2Responses];

export type CreateServerV2Data = {
  body?: V2CreateServerRequest;
  path?: never;
  query?: never;
  url: '/servers';
};

export type CreateServerV2Responses = {
  /**
   * Successful response
   */
  200: Server;
};

export type CreateServerV2Response = CreateServerV2Responses[keyof CreateServerV2Responses];

export type DeleteServerV2Data = {
  body?: never;
  path: {
    slug: Schema140;
  };
  query?: never;
  url: '/servers/{slug}';
};

export type DeleteServerV2Responses = {
  /**
   * Successful response
   */
  200: unknown;
};

export type GetServerV2Data = {
  body?: never;
  path: {
    slug: Schema140;
  };
  query?: never;
  url: '/servers/{slug}';
};

export type GetServerV2Responses = {
  /**
   * Successful response
   */
  200: Server;
};

export type GetServerV2Response = GetServerV2Responses[keyof GetServerV2Responses];

export type PatchServerV2Data = {
  body?: V2PatchServerRequest;
  path: {
    slug: Schema140;
  };
  query?: never;
  url: '/servers/{slug}';
};

export type PatchServerV2Responses = {
  /**
   * Successful response
   */
  200: Server;
};

export type PatchServerV2Response = PatchServerV2Responses[keyof PatchServerV2Responses];

export type UpdateServerV2Data = {
  body?: V2UpdateServerRequest;
  path: {
    slug: Schema140;
  };
  query?: never;
  url: '/servers/{slug}';
};

export type UpdateServerV2Responses = {
  /**
   * Successful response
   */
  200: Server;
};

export type UpdateServerV2Response = UpdateServerV2Responses[keyof UpdateServerV2Responses];

export type ListCredentialsV2Data = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Filter to credentials of a single server, by server ID
     */
    serverId?: Schema172;
  };
  url: '/credentials';
};

export type ListCredentialsV2Responses = {
  /**
   * Successful response
   */
  200: Schema295;
};

export type ListCredentialsV2Response = ListCredentialsV2Responses[keyof ListCredentialsV2Responses];

export type DeleteCredentialV2Data = {
  body?: never;
  path: {
    /**
     * ID of the credential
     */
    id: string;
  };
  query?: never;
  url: '/credentials/{id}';
};

export type DeleteCredentialV2Responses = {
  /**
   * Successful response
   */
  200: Schema295;
};

export type DeleteCredentialV2Response = DeleteCredentialV2Responses[keyof DeleteCredentialV2Responses];

export type GetCredentialV2Data = {
  body?: never;
  path: {
    /**
     * ID of the credential
     */
    id: string;
  };
  query?: never;
  url: '/credentials/{id}';
};

export type GetCredentialV2Responses = {
  /**
   * Successful response
   */
  200: CredentialDtoV2;
};

export type GetCredentialV2Response = GetCredentialV2Responses[keyof GetCredentialV2Responses];

export type GetCredentialSecretV2Data = {
  body?: never;
  path: {
    /**
     * ID of the credential
     */
    id: string;
  };
  query?: never;
  url: '/credentials/{id}/secret';
};

export type GetCredentialSecretV2Responses = {
  /**
   * Successful response
   */
  200: ServerCredentialsCredential;
};

export type GetCredentialSecretV2Response = GetCredentialSecretV2Responses[keyof GetCredentialSecretV2Responses];

export type RefreshCredentialV2Data = {
  body?: never;
  path: {
    /**
     * ID of the credential
     */
    id: string;
  };
  query?: never;
  url: '/credentials/{id}/refresh';
};

export type RefreshCredentialV2Responses = {
  /**
   * Successful response
   */
  200: CredentialRefreshResponse;
};

export type RefreshCredentialV2Response = RefreshCredentialV2Responses[keyof RefreshCredentialV2Responses];

export type ListCredentialAuditLogsV2Data = {
  body?: never;
  path: {
    /**
     * ID of the credential
     */
    credentialId: string;
  };
  query?: never;
  url: '/credentials/{credentialId}/audit-logs';
};

export type ListCredentialAuditLogsV2Responses = {
  /**
   * Successful response
   */
  200: PaginatedCredentialAuditLog;
};

export type ListCredentialAuditLogsV2Response =
  ListCredentialAuditLogsV2Responses[keyof ListCredentialAuditLogsV2Responses];

export type GetCredentialAuditLogV2Data = {
  body?: never;
  path: {
    /**
     * ID of the credential
     */
    credentialId: string;
    /**
     * ID of the audit log entry
     */
    auditLogId: string;
  };
  query?: never;
  url: '/credentials/{credentialId}/audit-logs/{auditLogId}';
};

export type GetCredentialAuditLogV2Responses = {
  /**
   * Successful response
   */
  200: CredentialAuditLog;
};

export type GetCredentialAuditLogV2Response = GetCredentialAuditLogV2Responses[keyof GetCredentialAuditLogV2Responses];
