/*! Client for the Gatana `v2` API: Gatana.

 Generated by gatana-codegen from the backend's OpenAPI document. Do not edit; change
 `operations.json` and run `just generate-rs` instead.*/
#![allow(clippy::all, unused_imports, irrefutable_let_patterns, dead_code)]
/// Path every operation of this API starts with.
pub const BASE_PATH: &str = "/api/v2";
/// Request and response types.
pub mod types {
    ///`CredentialDtoV2`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct CredentialDtoV2 {
        ///Time when the credential was authorized
        #[serde(rename = "authorizedAt")]
        pub authorized_at: ::std::string::String,
        ///Time when the credential record was created
        #[serde(rename = "createdAt")]
        pub created_at: ::std::string::String,
        ///Unique ID of the credential record
        pub id: ::std::string::String,
        ///Time when the credential was last used, or null if never used
        #[serde(
            rename = "lastUsedAt",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub last_used_at: ::std::option::Option<::std::string::String>,
        ///ID of the owning profile when scope is "profile", otherwise null
        #[serde(
            rename = "profileId",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub profile_id: ::std::option::Option<::std::string::String>,
        ///Name of the owning profile, or null
        #[serde(
            rename = "profileName",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub profile_name: ::std::option::Option<::std::string::String>,
        ///Scope that the credential applies to: server, user, or profile
        pub scope: CredentialDtoV2Scope,
        ///Slug of the server that the credential authorizes access to
        #[serde(rename = "serverSlug")]
        pub server_slug: ::std::string::String,
        ///ID of the tenant that owns the credential
        #[serde(rename = "tenantId")]
        pub tenant_id: ::std::string::String,
        ///Authorization method that the credential was created with
        #[serde(rename = "type")]
        pub type_: CredentialDtoV2Type,
        ///Time when the credential record was last updated
        #[serde(rename = "updatedAt")]
        pub updated_at: ::std::string::String,
        ///Email address of the owning user, or null
        #[serde(
            rename = "userEmail",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub user_email: ::std::option::Option<::std::string::String>,
        ///ID of the owning user, or null
        #[serde(
            rename = "userId",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub user_id: ::std::option::Option<::std::string::String>,
        ///Display name of the owning user, or null
        #[serde(
            rename = "userName",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub user_name: ::std::option::Option<::std::string::String>,
    }
    ///Scope that the credential applies to: server, user, or profile
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum CredentialDtoV2Scope {
        #[serde(rename = "server")]
        Server,
        #[serde(rename = "user")]
        User,
        #[serde(rename = "profile")]
        Profile,
    }
    impl ::std::fmt::Display for CredentialDtoV2Scope {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Server => f.write_str("server"),
                Self::User => f.write_str("user"),
                Self::Profile => f.write_str("profile"),
            }
        }
    }
    impl ::std::str::FromStr for CredentialDtoV2Scope {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "server" => Ok(Self::Server),
                "user" => Ok(Self::User),
                "profile" => Ok(Self::Profile),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for CredentialDtoV2Scope {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for CredentialDtoV2Scope {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Authorization method that the credential was created with
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum CredentialDtoV2Type {
        #[serde(rename = "oauth")]
        Oauth,
        #[serde(rename = "apikey")]
        Apikey,
        #[serde(rename = "oauth-client-credentials")]
        OauthClientCredentials,
    }
    impl ::std::fmt::Display for CredentialDtoV2Type {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Oauth => f.write_str("oauth"),
                Self::Apikey => f.write_str("apikey"),
                Self::OauthClientCredentials => f.write_str("oauth-client-credentials"),
            }
        }
    }
    impl ::std::str::FromStr for CredentialDtoV2Type {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "oauth" => Ok(Self::Oauth),
                "apikey" => Ok(Self::Apikey),
                "oauth-client-credentials" => Ok(Self::OauthClientCredentials),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for CredentialDtoV2Type {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for CredentialDtoV2Type {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct HostedTransportStorage {
        ///Whether the server gets a persistent volume
        pub enabled: bool,
    }
    ///Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct HostedTransportStorageOutput {
        ///Whether the server gets a persistent volume
        pub enabled: bool,
    }
    ///Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct HostedTransportTailscale {
        ///Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
        #[serde(rename = "authKey")]
        pub auth_key: ::std::string::String,
        ///Whether the server joins the tailnet
        pub enabled: bool,
        ///Machine name on the tailnet. Defaults to gatana-<server slug>
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub hostname: ::std::option::Option<::std::string::String>,
    }
    ///Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct HostedTransportTailscaleOutput {
        ///Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
        #[serde(rename = "authKey")]
        pub auth_key: ::std::string::String,
        ///Whether the server joins the tailnet
        pub enabled: bool,
        ///Machine name on the tailnet. Defaults to gatana-<server slug>
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub hostname: ::std::option::Option<::std::string::String>,
    }
    ///`ListCredentialsV2Response`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ListCredentialsV2Response {
        ///Credentials the caller can read, without secret values
        pub credentials: ::std::vec::Vec<CredentialDtoV2>,
    }
    ///`OAuthGrantType`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum OAuthGrantType {
        #[serde(rename = "authorization_code")]
        AuthorizationCode,
        #[serde(rename = "device_code")]
        DeviceCode,
    }
    impl ::std::fmt::Display for OAuthGrantType {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::AuthorizationCode => f.write_str("authorization_code"),
                Self::DeviceCode => f.write_str("device_code"),
            }
        }
    }
    impl ::std::str::FromStr for OAuthGrantType {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "authorization_code" => Ok(Self::AuthorizationCode),
                "device_code" => Ok(Self::DeviceCode),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for OAuthGrantType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for OAuthGrantType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`ServerAuthorization`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerAuthorization {
        ///Names of the API keys that the server expects
        #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
        pub apikeys: ::std::vec::Vec<::std::string::String>,
        ///Whether credentials are shared for the whole server or stored per user
        #[serde(rename = "credentialsScope")]
        pub credentials_scope: ServerAuthorizationCredentialsScope,
        ///Authorization method that the server uses
        pub method: ServerAuthorizationMethod,
        #[serde(
            rename = "toolRefreshCredentialPolicy",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub tool_refresh_credential_policy: ::std::option::Option<
            ToolRefreshCredentialPolicy,
        >,
    }
    ///Whether credentials are shared for the whole server or stored per user
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum ServerAuthorizationCredentialsScope {
        #[serde(rename = "server")]
        Server,
        #[serde(rename = "user")]
        User,
    }
    impl ::std::fmt::Display for ServerAuthorizationCredentialsScope {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Server => f.write_str("server"),
                Self::User => f.write_str("user"),
            }
        }
    }
    impl ::std::str::FromStr for ServerAuthorizationCredentialsScope {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "server" => Ok(Self::Server),
                "user" => Ok(Self::User),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ServerAuthorizationCredentialsScope {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for ServerAuthorizationCredentialsScope {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Authorization method that the server uses
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum ServerAuthorizationMethod {
        #[serde(rename = "none")]
        None,
        #[serde(rename = "oauth")]
        Oauth,
        #[serde(rename = "oauth-client-credentials")]
        OauthClientCredentials,
        #[serde(rename = "apikey")]
        Apikey,
    }
    impl ::std::fmt::Display for ServerAuthorizationMethod {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::None => f.write_str("none"),
                Self::Oauth => f.write_str("oauth"),
                Self::OauthClientCredentials => f.write_str("oauth-client-credentials"),
                Self::Apikey => f.write_str("apikey"),
            }
        }
    }
    impl ::std::str::FromStr for ServerAuthorizationMethod {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "none" => Ok(Self::None),
                "oauth" => Ok(Self::Oauth),
                "oauth-client-credentials" => Ok(Self::OauthClientCredentials),
                "apikey" => Ok(Self::Apikey),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ServerAuthorizationMethod {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ServerAuthorizationMethod {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`ServerAuthorizationOutput`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerAuthorizationOutput {
        ///Names of the API keys that the server expects
        #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
        pub apikeys: ::std::vec::Vec<::std::string::String>,
        ///Whether credentials are shared for the whole server or stored per user
        #[serde(rename = "credentialsScope")]
        pub credentials_scope: ServerAuthorizationOutputCredentialsScope,
        ///Authorization method that the server uses
        pub method: ServerAuthorizationOutputMethod,
        #[serde(rename = "toolRefreshCredentialPolicy")]
        pub tool_refresh_credential_policy: ToolRefreshCredentialPolicyOutput,
    }
    ///Whether credentials are shared for the whole server or stored per user
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum ServerAuthorizationOutputCredentialsScope {
        #[serde(rename = "server")]
        Server,
        #[serde(rename = "user")]
        User,
    }
    impl ::std::fmt::Display for ServerAuthorizationOutputCredentialsScope {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Server => f.write_str("server"),
                Self::User => f.write_str("user"),
            }
        }
    }
    impl ::std::str::FromStr for ServerAuthorizationOutputCredentialsScope {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "server" => Ok(Self::Server),
                "user" => Ok(Self::User),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ServerAuthorizationOutputCredentialsScope {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for ServerAuthorizationOutputCredentialsScope {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Authorization method that the server uses
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum ServerAuthorizationOutputMethod {
        #[serde(rename = "none")]
        None,
        #[serde(rename = "oauth")]
        Oauth,
        #[serde(rename = "oauth-client-credentials")]
        OauthClientCredentials,
        #[serde(rename = "apikey")]
        Apikey,
    }
    impl ::std::fmt::Display for ServerAuthorizationOutputMethod {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::None => f.write_str("none"),
                Self::Oauth => f.write_str("oauth"),
                Self::OauthClientCredentials => f.write_str("oauth-client-credentials"),
                Self::Apikey => f.write_str("apikey"),
            }
        }
    }
    impl ::std::str::FromStr for ServerAuthorizationOutputMethod {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "none" => Ok(Self::None),
                "oauth" => Ok(Self::Oauth),
                "oauth-client-credentials" => Ok(Self::OauthClientCredentials),
                "apikey" => Ok(Self::Apikey),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ServerAuthorizationOutputMethod {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for ServerAuthorizationOutputMethod {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`ServerCredentialsCredential`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(tag = "type")]
    pub enum ServerCredentialsCredential {
        #[serde(rename = "apikey")]
        Apikey {
            ///API keys as [name, value] pairs
            apikeys: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
        },
        #[serde(rename = "oauth")]
        Oauth {
            #[serde(rename = "tokenSet")]
            token_set: ServerCredentialsCredentialTokenSet,
        },
        #[serde(rename = "oauth-client-credentials")]
        OauthClientCredentials {
            #[serde(
                rename = "clientConfig",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            client_config: ::std::option::Option<
                ServerOAuthClientConfigurationClientCredentials,
            >,
            #[serde(
                rename = "tokenSet",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            token_set: ::std::option::Option<ServerCredentialsCredentialTokenSet>,
        },
    }
    ///OAuth tokens obtained from the authorization flow
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerCredentialsCredentialTokenSet {
        ///OAuth access token
        #[serde(rename = "accessToken")]
        pub access_token: ::std::string::String,
        ///Expiry time of the access token, as a Unix epoch timestamp
        #[serde(
            rename = "accessTokenExpiresAt",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub access_token_expires_at: ::std::option::Option<f64>,
        ///OpenID Connect ID token, if the authorization server issued one
        #[serde(
            rename = "idToken",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub id_token: ::std::option::Option<::std::string::String>,
        ///OAuth refresh token, if the authorization server issued one
        #[serde(
            rename = "refreshToken",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub refresh_token: ::std::option::Option<::std::string::String>,
    }
    ///`ServerOAuthClientConfiguration`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerOAuthClientConfiguration {
        ///Client authentication method used at the token endpoint
        #[serde(rename = "clientAuthMethod")]
        pub client_auth_method: ::std::string::String,
        ///OAuth client ID
        #[serde(
            rename = "clientId",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub client_id: ::std::option::Option<::std::string::String>,
        ///OAuth client secret
        #[serde(
            rename = "clientSecret",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub client_secret: ::std::option::Option<::std::string::String>,
        #[serde(rename = "grantType")]
        pub grant_type: OAuthGrantType,
        ///Space-separated OAuth scopes to request
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub scopes: ::std::option::Option<::std::string::String>,
    }
    ///Client configuration for OAuth client credentials
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerOAuthClientConfigurationClientCredentials {
        ///Client authentication method used at the token endpoint
        #[serde(rename = "clientAuthMethod")]
        pub client_auth_method: ::std::string::String,
        ///OAuth client ID
        #[serde(rename = "clientId")]
        pub client_id: ::std::string::String,
        ///OAuth client secret
        #[serde(rename = "clientSecret")]
        pub client_secret: ::std::string::String,
        ///Space-separated OAuth scopes to request
        pub scopes: ::std::string::String,
    }
    ///`ServerOAuthClientConfigurationOutput`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerOAuthClientConfigurationOutput {
        ///Client authentication method used at the token endpoint
        #[serde(rename = "clientAuthMethod")]
        pub client_auth_method: ::std::string::String,
        ///OAuth client ID
        #[serde(rename = "clientId")]
        pub client_id: ::std::string::String,
        ///OAuth client secret
        #[serde(rename = "clientSecret")]
        pub client_secret: ::std::string::String,
        #[serde(rename = "grantType")]
        pub grant_type: OAuthGrantType,
        ///Space-separated OAuth scopes to request
        pub scopes: ::std::string::String,
    }
    ///`ServerOAuthMetadata`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct ServerOAuthMetadata {
        #[serde(rename = "as", skip_serializing_if = "::std::option::Option::is_none")]
        pub as_: ::std::option::Option<ServerOAuthMetadataAs>,
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub resource: ::std::option::Option<ServerOAuthMetadataResource>,
    }
    ///Discovered authorization server metadata (RFC 8414)
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct ServerOAuthMetadataAs {
        ///URL of the authorization endpoint
        #[serde(
            rename = "authorizeEndpoint",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub authorize_endpoint: ::std::option::Option<::std::string::String>,
        ///Scopes that the authorization server supports
        #[serde(
            rename = "availableScopes",
            default,
            skip_serializing_if = "::std::vec::Vec::is_empty"
        )]
        pub available_scopes: ::std::vec::Vec<::std::string::String>,
        ///URL of the device authorization endpoint
        #[serde(
            rename = "deviceAuthorizationEndpoint",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub device_authorization_endpoint: ::std::option::Option<::std::string::String>,
        ///Extra query parameters to add to the authorization request
        #[serde(
            rename = "extraAuthorizationParameters",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub extra_authorization_parameters: ::std::option::Option<::std::string::String>,
        ///Issuer identifier of the authorization server
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub issuer: ::std::option::Option<::std::string::String>,
        ///URL where the authorization server metadata was fetched from
        #[serde(
            rename = "metadataUrl",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub metadata_url: ::std::option::Option<::std::string::String>,
        ///Reason why dynamic client registration is not available
        #[serde(
            rename = "noDynamicClientRegistrationReason",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub no_dynamic_client_registration_reason: ::std::option::Option<
            ::std::string::String,
        >,
        ///URL of the dynamic client registration endpoint
        #[serde(
            rename = "registrationEndpoint",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub registration_endpoint: ::std::option::Option<::std::string::String>,
        ///URL of the authorization server documentation
        #[serde(
            rename = "serviceDocumentation",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub service_documentation: ::std::option::Option<::std::string::String>,
        ///Client authentication methods that the token endpoint supports
        #[serde(
            rename = "supportedClientAuthMethods",
            default,
            skip_serializing_if = "::std::vec::Vec::is_empty"
        )]
        pub supported_client_auth_methods: ::std::vec::Vec<::std::string::String>,
        ///Whether the authorization server supports dynamic client registration
        #[serde(
            rename = "supportsDynamicClientRegistration",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub supports_dynamic_client_registration: ::std::option::Option<bool>,
        ///Whether the authorization server supports PKCE
        #[serde(
            rename = "supportsPKCE",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub supports_pkce: ::std::option::Option<bool>,
        ///URL of the token endpoint
        #[serde(
            rename = "tokenEndpoint",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub token_endpoint: ::std::option::Option<::std::string::String>,
    }
    ///`ServerOAuthMetadataOutput`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct ServerOAuthMetadataOutput {
        #[serde(rename = "as", skip_serializing_if = "::std::option::Option::is_none")]
        pub as_: ::std::option::Option<ServerOAuthMetadataOutputAs>,
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub resource: ::std::option::Option<ServerOAuthMetadataOutputResource>,
    }
    ///Discovered authorization server metadata (RFC 8414)
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerOAuthMetadataOutputAs {
        ///URL of the authorization endpoint
        #[serde(rename = "authorizeEndpoint")]
        pub authorize_endpoint: ::std::string::String,
        ///Scopes that the authorization server supports
        #[serde(rename = "availableScopes")]
        pub available_scopes: ::std::vec::Vec<::std::string::String>,
        ///URL of the device authorization endpoint
        #[serde(rename = "deviceAuthorizationEndpoint")]
        pub device_authorization_endpoint: ::std::string::String,
        ///Extra query parameters to add to the authorization request
        #[serde(rename = "extraAuthorizationParameters")]
        pub extra_authorization_parameters: ::std::string::String,
        ///Issuer identifier of the authorization server
        pub issuer: ::std::string::String,
        ///URL where the authorization server metadata was fetched from
        #[serde(rename = "metadataUrl")]
        pub metadata_url: ::std::string::String,
        ///Reason why dynamic client registration is not available
        #[serde(
            rename = "noDynamicClientRegistrationReason",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub no_dynamic_client_registration_reason: ::std::option::Option<
            ::std::string::String,
        >,
        ///URL of the dynamic client registration endpoint
        #[serde(
            rename = "registrationEndpoint",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub registration_endpoint: ::std::option::Option<::std::string::String>,
        ///URL of the authorization server documentation
        #[serde(rename = "serviceDocumentation")]
        pub service_documentation: ::std::string::String,
        ///Client authentication methods that the token endpoint supports
        #[serde(rename = "supportedClientAuthMethods")]
        pub supported_client_auth_methods: ::std::vec::Vec<::std::string::String>,
        ///Whether the authorization server supports dynamic client registration
        #[serde(rename = "supportsDynamicClientRegistration")]
        pub supports_dynamic_client_registration: bool,
        ///Whether the authorization server supports PKCE
        #[serde(rename = "supportsPKCE")]
        pub supports_pkce: bool,
        ///URL of the token endpoint
        #[serde(rename = "tokenEndpoint")]
        pub token_endpoint: ::std::string::String,
    }
    ///Discovered protected resource metadata (RFC 9728)
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct ServerOAuthMetadataOutputResource {
        ///Scopes that the protected resource supports
        #[serde(rename = "availableScopes")]
        pub available_scopes: ::std::vec::Vec<::std::string::String>,
        ///Resource identifier from the protected resource metadata
        pub id: ::std::string::String,
        ///URL where the protected resource metadata was fetched from
        #[serde(rename = "metadataUrl")]
        pub metadata_url: ::std::string::String,
    }
    ///Discovered protected resource metadata (RFC 9728)
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct ServerOAuthMetadataResource {
        ///Scopes that the protected resource supports
        #[serde(
            rename = "availableScopes",
            default,
            skip_serializing_if = "::std::vec::Vec::is_empty"
        )]
        pub available_scopes: ::std::vec::Vec<::std::string::String>,
        ///Resource identifier from the protected resource metadata
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub id: ::std::option::Option<::std::string::String>,
        ///URL where the protected resource metadata was fetched from
        #[serde(
            rename = "metadataUrl",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub metadata_url: ::std::option::Option<::std::string::String>,
    }
    ///`ServerVisibility`
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum ServerVisibility {
        #[serde(rename = "private")]
        Private,
        #[serde(rename = "organization")]
        Organization,
    }
    impl ::std::fmt::Display for ServerVisibility {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Private => f.write_str("private"),
                Self::Organization => f.write_str("organization"),
            }
        }
    }
    impl ::std::str::FromStr for ServerVisibility {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "private" => Ok(Self::Private),
                "organization" => Ok(Self::Organization),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ServerVisibility {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ServerVisibility {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct StdioTransportStorage {
        ///Whether the server gets a persistent volume
        pub enabled: bool,
    }
    ///Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct StdioTransportStorageOutput {
        ///Whether the server gets a persistent volume
        pub enabled: bool,
    }
    ///Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct StdioTransportTailscale {
        ///Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
        #[serde(rename = "authKey")]
        pub auth_key: ::std::string::String,
        ///Whether the server joins the tailnet
        pub enabled: bool,
        ///Machine name on the tailnet. Defaults to gatana-<server slug>
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub hostname: ::std::option::Option<::std::string::String>,
    }
    ///Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct StdioTransportTailscaleOutput {
        ///Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
        #[serde(rename = "authKey")]
        pub auth_key: ::std::string::String,
        ///Whether the server joins the tailnet
        pub enabled: bool,
        ///Machine name on the tailnet. Defaults to gatana-<server slug>
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub hostname: ::std::option::Option<::std::string::String>,
    }
    ///Controls how tool refresh is authorized. "server-scoped" means only server-scoped credentials are required, "skip" means refresh is done without authorization, and "any" means any available credentials (server, user, profile) can be used. Defaults to "server-scoped".
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum ToolRefreshCredentialPolicy {
        #[serde(rename = "server-scoped")]
        ServerScoped,
        #[serde(rename = "skip")]
        Skip,
        #[serde(rename = "any")]
        Any,
    }
    impl ::std::fmt::Display for ToolRefreshCredentialPolicy {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::ServerScoped => f.write_str("server-scoped"),
                Self::Skip => f.write_str("skip"),
                Self::Any => f.write_str("any"),
            }
        }
    }
    impl ::std::str::FromStr for ToolRefreshCredentialPolicy {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "server-scoped" => Ok(Self::ServerScoped),
                "skip" => Ok(Self::Skip),
                "any" => Ok(Self::Any),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ToolRefreshCredentialPolicy {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String> for ToolRefreshCredentialPolicy {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Controls how tool refresh is authorized. "server-scoped" means only server-scoped credentials are required, "skip" means refresh is done without authorization, and "any" means any available credentials (server, user, profile) can be used. Defaults to "server-scoped".
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum ToolRefreshCredentialPolicyOutput {
        #[serde(rename = "server-scoped")]
        ServerScoped,
        #[serde(rename = "skip")]
        Skip,
        #[serde(rename = "any")]
        Any,
    }
    impl ::std::fmt::Display for ToolRefreshCredentialPolicyOutput {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::ServerScoped => f.write_str("server-scoped"),
                Self::Skip => f.write_str("skip"),
                Self::Any => f.write_str("any"),
            }
        }
    }
    impl ::std::str::FromStr for ToolRefreshCredentialPolicyOutput {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "server-scoped" => Ok(Self::ServerScoped),
                "skip" => Ok(Self::Skip),
                "any" => Ok(Self::Any),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for ToolRefreshCredentialPolicyOutput {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for ToolRefreshCredentialPolicyOutput {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`V2CreateServerRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct V2CreateServerRequest {
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub authorization: ::std::option::Option<ServerAuthorization>,
        ///Read-only; accepted and ignored
        #[serde(
            rename = "createdAt",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub created_at: ::std::option::Option<::std::string::String>,
        ///Human-readable description of the server
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub description: ::std::option::Option<::std::string::String>,
        ///Firewall rules evaluated against tool calls to the server
        #[serde(
            rename = "firewallRules",
            default,
            skip_serializing_if = "::std::vec::Vec::is_empty"
        )]
        pub firewall_rules: ::std::vec::Vec<V2CreateServerRequestFirewallRulesItem>,
        ///Read-only; accepted and ignored
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub id: ::std::option::Option<::std::string::String>,
        ///Whether the server is enabled
        #[serde(
            rename = "isEnabled",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub is_enabled: ::std::option::Option<bool>,
        ///Whether large tool outputs are compressed before they are returned to the client
        #[serde(
            rename = "isOutputCompressionEnabled",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub is_output_compression_enabled: ::std::option::Option<bool>,
        ///Whether the compression transform step is applied to tool outputs
        #[serde(
            rename = "isOutputCompressionTransformEnabled",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub is_output_compression_transform_enabled: ::std::option::Option<bool>,
        ///Read-only; accepted and ignored
        #[serde(
            rename = "lastToolRefreshAt",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub last_tool_refresh_at: ::std::option::Option<::std::string::String>,
        ///Read-only; accepted and ignored
        #[serde(
            rename = "mcpProtocolDetectedAt",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub mcp_protocol_detected_at: ::std::option::Option<::std::string::String>,
        ///Read-only; accepted and ignored
        #[serde(
            rename = "mcpProtocolVersion",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub mcp_protocol_version: ::std::option::Option<::std::string::String>,
        ///OAuth client configuration, or null when not configured
        #[serde(
            rename = "oauthClientConfiguration",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub oauth_client_configuration: ::std::option::Option<
            ServerOAuthClientConfiguration,
        >,
        ///Discovered OAuth metadata, or null when not discovered
        #[serde(
            rename = "oauthMetadata",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub oauth_metadata: ::std::option::Option<ServerOAuthMetadata>,
        ///Minimum output size in bytes before compression is applied
        #[serde(
            rename = "outputCompressionThresholdBytes",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub output_compression_threshold_bytes: ::std::option::Option<i64>,
        ///Whether a progress notification resets the protocol timeout
        #[serde(
            rename = "resetTimeoutOnProgressNotification",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub reset_timeout_on_progress_notification: ::std::option::Option<bool>,
        ///URL-friendly name of the server, unique within the tenant
        pub slug: ::std::string::String,
        ///Read-only; accepted and ignored
        #[serde(
            rename = "tenantId",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub tenant_id: ::std::option::Option<::std::string::String>,
        ///Timeout in seconds for a single protocol request to the server
        #[serde(
            rename = "timeoutProtocol",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub timeout_protocol: ::std::option::Option<i64>,
        ///Total timeout in seconds for a tool call, including progress notifications
        #[serde(
            rename = "timeoutTotal",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub timeout_total: ::std::option::Option<i64>,
        ///Transport configuration used to connect to the server
        #[serde(
            rename = "transportConfig",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub transport_config: ::std::option::Option<
            V2CreateServerRequestTransportConfig,
        >,
        ///Transport type to create with a default configuration, used instead of transportConfig
        #[serde(
            rename = "transportConfigType",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub transport_config_type: ::std::option::Option<
            V2CreateServerRequestTransportConfigType,
        >,
        ///Read-only; accepted and ignored
        #[serde(
            rename = "updatedAt",
            skip_serializing_if = "::std::option::Option::is_none"
        )]
        pub updated_at: ::std::option::Option<::std::string::String>,
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub visibility: ::std::option::Option<ServerVisibility>,
    }
    ///`V2CreateServerRequestFirewallRulesItem`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct V2CreateServerRequestFirewallRulesItem {
        ///Action to take when the condition matches
        pub action: V2CreateServerRequestFirewallRulesItemAction,
        ///CEL representing the condition
        pub condition: ::std::string::String,
    }
    ///Action to take when the condition matches
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2CreateServerRequestFirewallRulesItemAction {
        #[serde(rename = "deny")]
        Deny,
        #[serde(rename = "modify")]
        Modify,
        #[serde(rename = "log")]
        Log,
    }
    impl ::std::fmt::Display for V2CreateServerRequestFirewallRulesItemAction {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Deny => f.write_str("deny"),
                Self::Modify => f.write_str("modify"),
                Self::Log => f.write_str("log"),
            }
        }
    }
    impl ::std::str::FromStr for V2CreateServerRequestFirewallRulesItemAction {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "deny" => Ok(Self::Deny),
                "modify" => Ok(Self::Modify),
                "log" => Ok(Self::Log),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for V2CreateServerRequestFirewallRulesItemAction {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2CreateServerRequestFirewallRulesItemAction {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Transport configuration used to connect to the server
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(tag = "type")]
    pub enum V2CreateServerRequestTransportConfig {
        #[serde(rename = "httpstreaming")]
        Httpstreaming {
            ///Extra HTTP headers to send with each request, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            headers: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            ///URL of the MCP streamable HTTP endpoint
            url: ::std::string::String,
        },
        #[serde(rename = "stdio")]
        Stdio {
            ///Command line that starts the MCP server process
            command: ::std::string::String,
            ///Docker image that the command runs in
            #[serde(
                rename = "dockerImage",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            docker_image: ::std::option::Option<::std::string::String>,
            ///Environment variables for the process, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            env: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            #[serde(
                rename = "healthCheck",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            health_check: ::std::option::Option<
                V2CreateServerRequestTransportConfigHealthCheck,
            >,
            ///Port that the process listens on when transport is HTTP-based
            #[serde(
                rename = "httpPort",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            http_port: ::std::option::Option<f64>,
            ///Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            limits: ::std::option::Option<V2CreateServerRequestTransportConfigLimits>,
            ///Resources reserved for the process: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            requests: ::std::option::Option<
                V2CreateServerRequestTransportConfigRequests,
            >,
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            storage: ::std::option::Option<StdioTransportStorage>,
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            tailscale: ::std::option::Option<StdioTransportTailscale>,
            ///Protocol that the launched process speaks
            transport: V2CreateServerRequestTransportConfigTransport,
            ///URL path of the MCP endpoint when transport is HTTP-based
            #[serde(
                rename = "urlPath",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            url_path: ::std::option::Option<::std::string::String>,
        },
        #[serde(rename = "sse")]
        Sse {
            ///Extra HTTP headers to send with each request, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            headers: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            ///URL of the MCP SSE endpoint
            url: ::std::string::String,
        },
        #[serde(rename = "hosted")]
        Hosted {
            ///Environment variables for the hosted runtime, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            env: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            ///Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            limits: ::std::option::Option<V2CreateServerRequestTransportConfigLimits>,
            ///Resources reserved for the hosted runtime: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            requests: ::std::option::Option<
                V2CreateServerRequestTransportConfigRequests,
            >,
            ///Runtime that executes the hosted tool functions
            runtime: V2CreateServerRequestTransportConfigRuntime,
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            storage: ::std::option::Option<HostedTransportStorage>,
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            tailscale: ::std::option::Option<HostedTransportTailscale>,
        },
        #[serde(rename = "openapi")]
        Openapi {
            ///Base URL for the API requests generated from the spec
            #[serde(
                rename = "baseUrl",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            base_url: ::std::option::Option<::std::string::String>,
            ///Extra HTTP headers to send with each request, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            headers: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            ///How the OpenAPI spec is supplied: from a URL or as inline content
            method: V2CreateServerRequestTransportConfigMethod,
            ///Inline OpenAPI spec content, used when method is "spec"
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            spec: ::std::option::Option<::std::string::String>,
            ///URL to fetch the OpenAPI spec from, used when method is "specUrl"
            #[serde(
                rename = "specUrl",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            spec_url: ::std::option::Option<::std::string::String>,
        },
    }
    ///HTTP health check configuration for the process
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct V2CreateServerRequestTransportConfigHealthCheck {
        ///Seconds to wait before the first health check
        #[serde(
            rename = "delaySeconds",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub delay_seconds: ::std::option::Option<i64>,
        ///Whether the health check is active
        pub enabled: bool,
        ///Number of consecutive failures before the process counts as unhealthy
        #[serde(
            rename = "failureThreshold",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub failure_threshold: ::std::option::Option<i64>,
        ///Seconds between health checks
        #[serde(
            rename = "intervalSeconds",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub interval_seconds: ::std::option::Option<i64>,
        ///URL that the health check polls
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub url: ::std::option::Option<::std::string::String>,
    }
    ///`V2CreateServerRequestTransportConfigLimits`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct V2CreateServerRequestTransportConfigLimits {
        ///CPU limit in Kubernetes quantity format (e.g. "500m" or "1")
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub cpu: ::std::option::Option<::std::string::String>,
        ///Memory limit in Kubernetes quantity format (e.g. "512Mi" or "1Gi")
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub memory: ::std::option::Option<::std::string::String>,
    }
    ///How the OpenAPI spec is supplied: from a URL or as inline content
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2CreateServerRequestTransportConfigMethod {
        #[serde(rename = "specUrl")]
        SpecUrl,
        #[serde(rename = "spec")]
        Spec,
    }
    impl ::std::fmt::Display for V2CreateServerRequestTransportConfigMethod {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::SpecUrl => f.write_str("specUrl"),
                Self::Spec => f.write_str("spec"),
            }
        }
    }
    impl ::std::str::FromStr for V2CreateServerRequestTransportConfigMethod {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "specUrl" => Ok(Self::SpecUrl),
                "spec" => Ok(Self::Spec),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for V2CreateServerRequestTransportConfigMethod {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2CreateServerRequestTransportConfigMethod {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`V2CreateServerRequestTransportConfigRequests`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct V2CreateServerRequestTransportConfigRequests {
        ///CPU reserved for the deployment, in Kubernetes quantity format (e.g. "250m" or "1"). This is the minimum the deployment is guaranteed when the hardware is busy; when capacity is free it may use more. Reserved capacity counts against the organization total even while the server idles, so keep it at what the server needs, not what it may burst to
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub cpu: ::std::option::Option<::std::string::String>,
        ///Memory reserved for the deployment, in Kubernetes quantity format (e.g. "384Mi" or "1Gi"). Unlike CPU this is also the hard ceiling: a process that exceeds it is terminated
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub memory: ::std::option::Option<::std::string::String>,
    }
    ///Runtime that executes the hosted tool functions
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2CreateServerRequestTransportConfigRuntime {
        #[serde(rename = "node24")]
        Node24,
        #[serde(rename = "python313")]
        Python313,
    }
    impl ::std::fmt::Display for V2CreateServerRequestTransportConfigRuntime {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Node24 => f.write_str("node24"),
                Self::Python313 => f.write_str("python313"),
            }
        }
    }
    impl ::std::str::FromStr for V2CreateServerRequestTransportConfigRuntime {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "node24" => Ok(Self::Node24),
                "python313" => Ok(Self::Python313),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for V2CreateServerRequestTransportConfigRuntime {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2CreateServerRequestTransportConfigRuntime {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Protocol that the launched process speaks
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2CreateServerRequestTransportConfigTransport {
        #[serde(rename = "sse")]
        Sse,
        #[serde(rename = "httpstreaming")]
        Httpstreaming,
        #[serde(rename = "stdio")]
        Stdio,
    }
    impl ::std::fmt::Display for V2CreateServerRequestTransportConfigTransport {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Sse => f.write_str("sse"),
                Self::Httpstreaming => f.write_str("httpstreaming"),
                Self::Stdio => f.write_str("stdio"),
            }
        }
    }
    impl ::std::str::FromStr for V2CreateServerRequestTransportConfigTransport {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "sse" => Ok(Self::Sse),
                "httpstreaming" => Ok(Self::Httpstreaming),
                "stdio" => Ok(Self::Stdio),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str>
    for V2CreateServerRequestTransportConfigTransport {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2CreateServerRequestTransportConfigTransport {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Transport type to create with a default configuration, used instead of transportConfig
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2CreateServerRequestTransportConfigType {
        #[serde(rename = "httpstreaming")]
        Httpstreaming,
        #[serde(rename = "sse")]
        Sse,
        #[serde(rename = "stdio")]
        Stdio,
        #[serde(rename = "hosted")]
        Hosted,
        #[serde(rename = "openapi")]
        Openapi,
    }
    impl ::std::fmt::Display for V2CreateServerRequestTransportConfigType {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Httpstreaming => f.write_str("httpstreaming"),
                Self::Sse => f.write_str("sse"),
                Self::Stdio => f.write_str("stdio"),
                Self::Hosted => f.write_str("hosted"),
                Self::Openapi => f.write_str("openapi"),
            }
        }
    }
    impl ::std::str::FromStr for V2CreateServerRequestTransportConfigType {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "httpstreaming" => Ok(Self::Httpstreaming),
                "sse" => Ok(Self::Sse),
                "stdio" => Ok(Self::Stdio),
                "hosted" => Ok(Self::Hosted),
                "openapi" => Ok(Self::Openapi),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for V2CreateServerRequestTransportConfigType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2CreateServerRequestTransportConfigType {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`V2ListServersResponse`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct V2ListServersResponse {
        pub servers: ::std::vec::Vec<V2ServerDto>,
    }
    ///`V2PatchServerRequest`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(transparent)]
    pub struct V2PatchServerRequest(
        pub ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    );
    impl ::std::ops::Deref for V2PatchServerRequest {
        type Target = ::serde_json::Map<::std::string::String, ::serde_json::Value>;
        fn deref(
            &self,
        ) -> &::serde_json::Map<::std::string::String, ::serde_json::Value> {
            &self.0
        }
    }
    impl ::std::convert::From<V2PatchServerRequest>
    for ::serde_json::Map<::std::string::String, ::serde_json::Value> {
        fn from(value: V2PatchServerRequest) -> Self {
            value.0
        }
    }
    impl ::std::convert::From<
        ::serde_json::Map<::std::string::String, ::serde_json::Value>,
    > for V2PatchServerRequest {
        fn from(
            value: ::serde_json::Map<::std::string::String, ::serde_json::Value>,
        ) -> Self {
            Self(value)
        }
    }
    ///`V2ServerDto`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct V2ServerDto {
        pub authorization: ServerAuthorizationOutput,
        ///Time when the server was created
        #[serde(rename = "createdAt")]
        pub created_at: ::std::string::String,
        ///Human-readable description of the server
        pub description: ::std::string::String,
        ///Firewall rules evaluated against tool calls to the server
        #[serde(rename = "firewallRules")]
        pub firewall_rules: ::std::vec::Vec<V2ServerDtoFirewallRulesItem>,
        ///Unique ID of the server
        pub id: ::std::string::String,
        ///Whether the server is enabled
        #[serde(rename = "isEnabled")]
        pub is_enabled: bool,
        ///Whether large tool outputs are compressed before they are returned to the client
        #[serde(rename = "isOutputCompressionEnabled")]
        pub is_output_compression_enabled: bool,
        ///Whether the compression transform step is applied to tool outputs
        #[serde(rename = "isOutputCompressionTransformEnabled")]
        pub is_output_compression_transform_enabled: bool,
        ///Time of the last tool refresh, or null if tools were never refreshed
        #[serde(
            rename = "lastToolRefreshAt",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub last_tool_refresh_at: ::std::option::Option<::std::string::String>,
        ///Time when the protocol version was last detected, or null if never
        #[serde(
            rename = "mcpProtocolDetectedAt",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub mcp_protocol_detected_at: ::std::option::Option<::std::string::String>,
        ///MCP protocol version the server was last seen to speak, or empty if not yet detected
        #[serde(rename = "mcpProtocolVersion")]
        pub mcp_protocol_version: ::std::string::String,
        ///OAuth client configuration, or null when not configured
        #[serde(
            rename = "oauthClientConfiguration",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub oauth_client_configuration: ::std::option::Option<
            ServerOAuthClientConfigurationOutput,
        >,
        ///Discovered OAuth metadata, or null when not discovered
        #[serde(
            rename = "oauthMetadata",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub oauth_metadata: ::std::option::Option<ServerOAuthMetadataOutput>,
        ///Minimum output size in bytes before compression is applied
        #[serde(rename = "outputCompressionThresholdBytes")]
        pub output_compression_threshold_bytes: i64,
        ///Whether a progress notification resets the protocol timeout
        #[serde(rename = "resetTimeoutOnProgressNotification")]
        pub reset_timeout_on_progress_notification: bool,
        ///URL-friendly name of the server, unique within the tenant
        pub slug: ::std::string::String,
        ///ID of the tenant that owns the server
        #[serde(rename = "tenantId")]
        pub tenant_id: ::std::string::String,
        ///Timeout in seconds for a single protocol request to the server
        #[serde(rename = "timeoutProtocol")]
        pub timeout_protocol: i64,
        ///Total timeout in seconds for a tool call, including progress notifications
        #[serde(rename = "timeoutTotal")]
        pub timeout_total: i64,
        ///Transport configuration used to connect to the server
        #[serde(rename = "transportConfig")]
        pub transport_config: V2ServerDtoTransportConfig,
        ///Time when the server was last updated
        #[serde(rename = "updatedAt")]
        pub updated_at: ::std::string::String,
        pub visibility: ServerVisibility,
    }
    ///`V2ServerDtoFirewallRulesItem`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct V2ServerDtoFirewallRulesItem {
        ///Action to take when the condition matches
        pub action: V2ServerDtoFirewallRulesItemAction,
        ///CEL representing the condition
        pub condition: ::std::string::String,
    }
    ///Action to take when the condition matches
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2ServerDtoFirewallRulesItemAction {
        #[serde(rename = "deny")]
        Deny,
        #[serde(rename = "modify")]
        Modify,
        #[serde(rename = "log")]
        Log,
    }
    impl ::std::fmt::Display for V2ServerDtoFirewallRulesItemAction {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Deny => f.write_str("deny"),
                Self::Modify => f.write_str("modify"),
                Self::Log => f.write_str("log"),
            }
        }
    }
    impl ::std::str::FromStr for V2ServerDtoFirewallRulesItemAction {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "deny" => Ok(Self::Deny),
                "modify" => Ok(Self::Modify),
                "log" => Ok(Self::Log),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for V2ServerDtoFirewallRulesItemAction {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2ServerDtoFirewallRulesItemAction {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Transport configuration used to connect to the server
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    #[serde(tag = "type")]
    pub enum V2ServerDtoTransportConfig {
        #[serde(rename = "httpstreaming")]
        Httpstreaming {
            ///Extra HTTP headers to send with each request, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            headers: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            ///URL of the MCP streamable HTTP endpoint
            url: ::std::string::String,
        },
        #[serde(rename = "stdio")]
        Stdio {
            ///Command line that starts the MCP server process
            command: ::std::string::String,
            ///Docker image that the command runs in
            #[serde(
                rename = "dockerImage",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            docker_image: ::std::option::Option<::std::string::String>,
            ///Environment variables for the process, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            env: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            #[serde(
                rename = "healthCheck",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            health_check: ::std::option::Option<V2ServerDtoTransportConfigHealthCheck>,
            ///Port that the process listens on when transport is HTTP-based
            #[serde(
                rename = "httpPort",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            http_port: ::std::option::Option<f64>,
            ///Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            limits: ::std::option::Option<V2ServerDtoTransportConfigLimits>,
            ///Resources reserved for the process: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            requests: ::std::option::Option<V2ServerDtoTransportConfigRequests>,
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            storage: ::std::option::Option<StdioTransportStorageOutput>,
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            tailscale: ::std::option::Option<StdioTransportTailscaleOutput>,
            ///Protocol that the launched process speaks
            transport: V2ServerDtoTransportConfigTransport,
            ///URL path of the MCP endpoint when transport is HTTP-based
            #[serde(
                rename = "urlPath",
                skip_serializing_if = "::std::option::Option::is_none"
            )]
            url_path: ::std::option::Option<::std::string::String>,
        },
        #[serde(rename = "sse")]
        Sse {
            ///Extra HTTP headers to send with each request, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            headers: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            ///URL of the MCP SSE endpoint
            url: ::std::string::String,
        },
        #[serde(rename = "self")]
        Self_ {
            ///ID of the built-in server implementation
            id: ::std::string::String,
        },
        #[serde(rename = "hosted")]
        Hosted {
            ///Environment variables for the hosted runtime, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            env: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            ///Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            limits: ::std::option::Option<V2ServerDtoTransportConfigLimits>,
            ///Resources reserved for the hosted runtime: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            requests: ::std::option::Option<V2ServerDtoTransportConfigRequests>,
            ///Runtime that executes the hosted tool functions
            runtime: V2ServerDtoTransportConfigRuntime,
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            storage: ::std::option::Option<HostedTransportStorageOutput>,
            #[serde(skip_serializing_if = "::std::option::Option::is_none")]
            tailscale: ::std::option::Option<HostedTransportTailscaleOutput>,
        },
        #[serde(rename = "openapi")]
        Openapi {
            ///Base URL for the API requests generated from the spec
            #[serde(rename = "baseUrl")]
            base_url: ::std::string::String,
            ///Extra HTTP headers to send with each request, as [name, value] pairs
            #[serde(default, skip_serializing_if = "::std::vec::Vec::is_empty")]
            headers: ::std::vec::Vec<(::std::string::String, ::std::string::String)>,
            ///How the OpenAPI spec is supplied: from a URL or as inline content
            method: V2ServerDtoTransportConfigMethod,
            ///Inline OpenAPI spec content, used when method is "spec"
            spec: ::std::string::String,
            ///URL to fetch the OpenAPI spec from, used when method is "specUrl"
            #[serde(rename = "specUrl")]
            spec_url: ::std::string::String,
        },
    }
    ///HTTP health check configuration for the process
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug)]
    pub struct V2ServerDtoTransportConfigHealthCheck {
        ///Seconds to wait before the first health check
        #[serde(
            rename = "delaySeconds",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub delay_seconds: ::std::option::Option<i64>,
        ///Whether the health check is active
        pub enabled: bool,
        ///Number of consecutive failures before the process counts as unhealthy
        #[serde(
            rename = "failureThreshold",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub failure_threshold: ::std::option::Option<i64>,
        ///Seconds between health checks
        #[serde(
            rename = "intervalSeconds",
            deserialize_with = "::std::option::Option::deserialize"
        )]
        pub interval_seconds: ::std::option::Option<i64>,
        ///URL that the health check polls
        pub url: ::std::string::String,
    }
    ///`V2ServerDtoTransportConfigLimits`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct V2ServerDtoTransportConfigLimits {
        ///CPU limit in Kubernetes quantity format (e.g. "500m" or "1")
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub cpu: ::std::option::Option<::std::string::String>,
        ///Memory limit in Kubernetes quantity format (e.g. "512Mi" or "1Gi")
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub memory: ::std::option::Option<::std::string::String>,
    }
    ///How the OpenAPI spec is supplied: from a URL or as inline content
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2ServerDtoTransportConfigMethod {
        #[serde(rename = "specUrl")]
        SpecUrl,
        #[serde(rename = "spec")]
        Spec,
    }
    impl ::std::fmt::Display for V2ServerDtoTransportConfigMethod {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::SpecUrl => f.write_str("specUrl"),
                Self::Spec => f.write_str("spec"),
            }
        }
    }
    impl ::std::str::FromStr for V2ServerDtoTransportConfigMethod {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "specUrl" => Ok(Self::SpecUrl),
                "spec" => Ok(Self::Spec),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for V2ServerDtoTransportConfigMethod {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2ServerDtoTransportConfigMethod {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///`V2ServerDtoTransportConfigRequests`
    #[derive(::serde::Deserialize, ::serde::Serialize, Clone, Debug, Default)]
    pub struct V2ServerDtoTransportConfigRequests {
        ///CPU reserved for the deployment, in Kubernetes quantity format (e.g. "250m" or "1"). This is the minimum the deployment is guaranteed when the hardware is busy; when capacity is free it may use more. Reserved capacity counts against the organization total even while the server idles, so keep it at what the server needs, not what it may burst to
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub cpu: ::std::option::Option<::std::string::String>,
        ///Memory reserved for the deployment, in Kubernetes quantity format (e.g. "384Mi" or "1Gi"). Unlike CPU this is also the hard ceiling: a process that exceeds it is terminated
        #[serde(skip_serializing_if = "::std::option::Option::is_none")]
        pub memory: ::std::option::Option<::std::string::String>,
    }
    ///Runtime that executes the hosted tool functions
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2ServerDtoTransportConfigRuntime {
        #[serde(rename = "node24")]
        Node24,
        #[serde(rename = "python313")]
        Python313,
    }
    impl ::std::fmt::Display for V2ServerDtoTransportConfigRuntime {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Node24 => f.write_str("node24"),
                Self::Python313 => f.write_str("python313"),
            }
        }
    }
    impl ::std::str::FromStr for V2ServerDtoTransportConfigRuntime {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "node24" => Ok(Self::Node24),
                "python313" => Ok(Self::Python313),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for V2ServerDtoTransportConfigRuntime {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2ServerDtoTransportConfigRuntime {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    ///Protocol that the launched process speaks
    #[derive(
        ::serde::Deserialize,
        ::serde::Serialize,
        Clone,
        Copy,
        Debug,
        Eq,
        Hash,
        Ord,
        PartialEq,
        PartialOrd
    )]
    pub enum V2ServerDtoTransportConfigTransport {
        #[serde(rename = "sse")]
        Sse,
        #[serde(rename = "httpstreaming")]
        Httpstreaming,
        #[serde(rename = "stdio")]
        Stdio,
    }
    impl ::std::fmt::Display for V2ServerDtoTransportConfigTransport {
        fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
            match *self {
                Self::Sse => f.write_str("sse"),
                Self::Httpstreaming => f.write_str("httpstreaming"),
                Self::Stdio => f.write_str("stdio"),
            }
        }
    }
    impl ::std::str::FromStr for V2ServerDtoTransportConfigTransport {
        type Err = self::error::ConversionError;
        fn from_str(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            match value {
                "sse" => Ok(Self::Sse),
                "httpstreaming" => Ok(Self::Httpstreaming),
                "stdio" => Ok(Self::Stdio),
                _ => Err("invalid value".into()),
            }
        }
    }
    impl ::std::convert::TryFrom<&str> for V2ServerDtoTransportConfigTransport {
        type Error = self::error::ConversionError;
        fn try_from(
            value: &str,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    impl ::std::convert::TryFrom<::std::string::String>
    for V2ServerDtoTransportConfigTransport {
        type Error = self::error::ConversionError;
        fn try_from(
            value: ::std::string::String,
        ) -> ::std::result::Result<Self, self::error::ConversionError> {
            value.parse()
        }
    }
    /// Error types.
    pub mod error {
        /// Error from a `TryFrom` or `FromStr` implementation.
        pub struct ConversionError(::std::borrow::Cow<'static, str>);
        impl ::std::error::Error for ConversionError {}
        impl ::std::fmt::Display for ConversionError {
            fn fmt(
                &self,
                f: &mut ::std::fmt::Formatter<'_>,
            ) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Display::fmt(&self.0, f)
            }
        }
        impl ::std::fmt::Debug for ConversionError {
            fn fmt(
                &self,
                f: &mut ::std::fmt::Formatter<'_>,
            ) -> Result<(), ::std::fmt::Error> {
                ::std::fmt::Debug::fmt(&self.0, f)
            }
        }
        impl From<&'static str> for ConversionError {
            fn from(value: &'static str) -> Self {
                Self(value.into())
            }
        }
        impl From<String> for ConversionError {
            fn from(value: String) -> Self {
                Self(value.into())
            }
        }
    }
}
/// Optional query parameters, one struct per operation that takes any.
pub mod query {
    /// Optional query parameters of `listCredentialsV2`.
    #[derive(Debug, Clone, Default)]
    pub struct ListCredentialsV2 {
        /// `serverId`. Filter to credentials of a single server, by server ID
        pub server_id: Option<String>,
    }
    impl ListCredentialsV2 {
        pub fn apply<'c, T>(&self, mut call: crate::Call<'c, T>) -> crate::Call<'c, T> {
            if let Some(value) = &self.server_id {
                call = call.query("serverId", value);
            }
            call
        }
    }
}
use types::*;
/// The operations of this API.
#[derive(Clone, Copy)]
pub struct Api<'a> {
    client: &'a crate::Client,
}
impl<'a> Api<'a> {
    pub fn new(client: &'a crate::Client) -> Self {
        Self { client }
    }
    /** `GET /servers`

 List all MCP servers the caller has access to*/
    pub fn list_servers_v2(&self) -> crate::Call<'a, V2ListServersResponse> {
        let path = format!("{}/servers", BASE_PATH);
        let call = crate::Call::new(self.client, ::reqwest::Method::GET, path);
        call
    }
    /** `GET /servers/{slug}`

 Get a single MCP server. The response body can be PUT back to update the server*/
    pub fn get_server_v2(&self, slug: &str) -> crate::Call<'a, V2ServerDto> {
        let slug = crate::encode_path_segment(slug);
        let path = format!("{}/servers/{}", BASE_PATH, slug);
        let call = crate::Call::new(self.client, ::reqwest::Method::GET, path);
        call
    }
    /** `POST /servers`

 Create a new MCP server. Requires `slug` and `transportConfig`. All other fields are optional with sensible defaults. Read-only fields are silently ignored*/
    pub fn create_server_v2(
        &self,
        body: &V2CreateServerRequest,
    ) -> crate::Call<'a, V2ServerDto> {
        let path = format!("{}/servers", BASE_PATH);
        let call = crate::Call::new(self.client, ::reqwest::Method::POST, path);
        call.json(body)
    }
    /// `POST /servers` with a body that is sent as given, unchecked.
    pub fn create_server_v2_raw(
        &self,
        body: ::serde_json::Value,
    ) -> crate::Call<'a, V2ServerDto> {
        let path = format!("{}/servers", BASE_PATH);
        let call = crate::Call::new(self.client, ::reqwest::Method::POST, path);
        call.json_value(body)
    }
    /** `PATCH /servers/{slug}`

 Partially update an MCP server using JSON Merge Patch (RFC 7396). Send only the fields to change. Explicit `null` clears nullable fields (oauthMetadata, oauthClientConfiguration). Absent fields are untouched. Read-only fields are silently ignored*/
    pub fn patch_server_v2(
        &self,
        slug: &str,
        body: &V2PatchServerRequest,
    ) -> crate::Call<'a, V2ServerDto> {
        let slug = crate::encode_path_segment(slug);
        let path = format!("{}/servers/{}", BASE_PATH, slug);
        let call = crate::Call::new(self.client, ::reqwest::Method::PATCH, path);
        call.json(body)
    }
    /// `PATCH /servers/{slug}` with a body that is sent as given, unchecked.
    pub fn patch_server_v2_raw(
        &self,
        slug: &str,
        body: ::serde_json::Value,
    ) -> crate::Call<'a, V2ServerDto> {
        let slug = crate::encode_path_segment(slug);
        let path = format!("{}/servers/{}", BASE_PATH, slug);
        let call = crate::Call::new(self.client, ::reqwest::Method::PATCH, path);
        call.json_value(body)
    }
    /** `GET /credentials`

 List the credentials the caller can read, optionally filtered by server. Secret values are not included*/
    pub fn list_credentials_v2(
        &self,
        query: &query::ListCredentialsV2,
    ) -> crate::Call<'a, ListCredentialsV2Response> {
        let path = format!("{}/credentials", BASE_PATH);
        let call = crate::Call::new(self.client, ::reqwest::Method::GET, path);
        let call = query.apply(call);
        call
    }
    /** `GET /credentials/{id}/secret`

 Reveal the secret values of a credential. Requires the read-secret permission on the credential*/
    pub fn get_credential_secret_v2(
        &self,
        id: &str,
    ) -> crate::Call<'a, ServerCredentialsCredential> {
        let id = crate::encode_path_segment(id);
        let path = format!("{}/credentials/{}/secret", BASE_PATH, id);
        let call = crate::Call::new(self.client, ::reqwest::Method::GET, path);
        call
    }
}
