// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://{YOUR_ORG_ID}.gatana.ai/api/v2' | (string & {});
};

export type V2CreateServerRequest = {
    slug: Schema0;
    transportConfig?: Schema1;
    transportConfigType?: Schema60;
    description?: Schema63;
    authorization?: Schema65;
    oauthMetadata?: Schema74;
    oauthClientConfiguration?: Schema97;
    isEnabled?: Schema112;
    timeoutProtocol?: Schema114;
    timeoutTotal?: Schema116;
    resetTimeoutOnProgressNotification?: Schema118;
    isOutputCompressionEnabled?: Schema120;
    isOutputCompressionTransformEnabled?: Schema122;
    outputCompressionThresholdBytes?: Schema124;
    firewallRules?: Schema126;
    visibility?: Schema129;
    id?: Schema130;
    tenantId?: Schema132;
    lastToolRefreshAt?: Schema134;
    mcpProtocolVersion?: Schema136;
    mcpProtocolDetectedAt?: Schema138;
    createdAt?: Schema140;
    updatedAt?: Schema142;
};

export type HttpStreamingTransportConfig = {
    type: Schema3;
    url: Schema4;
    headers?: Schema5;
};

export type StdioTransportConfig = {
    type: Schema7;
    command: Schema8;
    dockerImage?: Schema9;
    env?: Schema11;
    transport: Schema13;
    httpPort?: Schema14;
    urlPath?: Schema16;
    healthCheck?: Schema18;
    limits?: Schema24;
    requests?: Schema28;
    storage?: StdioTransportStorage;
    tailscale?: StdioTransportTailscale;
};

/**
 * Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
 */
export type StdioTransportStorage = Schema32 | null;

/**
 * Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
 */
export type StdioTransportTailscale = Schema33 | null;

export type SseTransportConfig = {
    type: Schema35;
    url: Schema36;
    headers?: Schema37;
};

export type HostedTransportConfig = {
    type: Schema39;
    runtime: Schema40;
    env?: Schema41;
    limits?: Schema43;
    requests?: Schema45;
    storage?: HostedTransportStorage;
    tailscale?: HostedTransportTailscale;
};

/**
 * Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
 */
export type HostedTransportStorage = Schema47 | null;

/**
 * Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
 */
export type HostedTransportTailscale = Schema48 | null;

export type OpenApiTransportConfig = {
    type: Schema50;
    method: Schema51;
    specUrl?: Schema52;
    spec?: Schema54;
    baseUrl?: Schema56;
    headers?: Schema58;
};

/**
 * Controls how tool refresh is authorized. "server-scoped" means only server-scoped credentials are required, "skip" means refresh is done without authorization, and "any" means any available credentials (server, user, profile) can be used. Defaults to "server-scoped".
 */
export type ToolRefreshCredentialPolicy = Schema72;

export type ServerAuthorization = {
    method: Schema66;
    credentialsScope: Schema67;
    apikeys?: Schema70;
    toolRefreshCredentialPolicy?: ToolRefreshCredentialPolicy;
};

export type ServerOAuthMetadata = {
    resource?: Schema76;
    as?: Schema81;
};

export type ServerOAuthClientConfiguration = {
    clientId?: Schema99;
    clientSecret?: Schema101;
    grantType: Schema103;
    clientAuthMethod: Schema104;
    scopes?: Schema109;
};

export type OAuthGrantType = 'authorization_code' | 'device_code';

export type ServerVisibility = 'private' | 'organization';

export type V2UpdateServerRequest = {
    slug?: Schema145;
    description?: Schema63;
    authorization?: Schema65;
    transportConfig?: Schema149;
    oauthMetadata?: Schema74;
    oauthClientConfiguration?: Schema97;
    isEnabled?: Schema112;
    timeoutProtocol?: Schema114;
    timeoutTotal?: Schema116;
    resetTimeoutOnProgressNotification?: Schema118;
    isOutputCompressionEnabled?: Schema120;
    isOutputCompressionTransformEnabled?: Schema122;
    outputCompressionThresholdBytes?: Schema124;
    firewallRules?: Schema126;
    visibility?: Schema129;
    id?: Schema162;
    tenantId?: Schema164;
    name?: Schema166;
    lastToolRefreshAt?: Schema168;
    mcpProtocolVersion?: Schema170;
    mcpProtocolDetectedAt?: Schema172;
    createdAt?: Schema174;
    updatedAt?: Schema176;
};

export type V2PatchServerRequest = {
    [key in Schema178]?: Schema179;
};

/**
 * URL-friendly name of the server, unique within the tenant
 */
export type Schema0 = string;

/**
 * Transport configuration used to connect to the server
 */
export type Schema1 = Schema2;

export type Schema2 = HttpStreamingTransportConfig | StdioTransportConfig | SseTransportConfig | HostedTransportConfig | OpenApiTransportConfig;

/**
 * Transport type discriminator, always "httpstreaming"
 */
export type Schema3 = 'httpstreaming';

/**
 * URL of the MCP streamable HTTP endpoint
 */
export type Schema4 = string;

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema5 = Schema6;

export type Schema6 = Array<[
    string,
    string
]>;

/**
 * Transport type discriminator, always "stdio"
 */
export type Schema7 = 'stdio';

/**
 * Command line that starts the MCP server process
 */
export type Schema8 = string;

/**
 * Docker image that the command runs in
 */
export type Schema9 = Schema10;

export type Schema10 = string;

/**
 * Environment variables for the process, as [name, value] pairs
 */
export type Schema11 = Schema12;

export type Schema12 = Array<[
    string,
    string
]>;

/**
 * Protocol that the launched process speaks
 */
export type Schema13 = 'sse' | 'httpstreaming' | 'stdio';

/**
 * Port that the process listens on when transport is HTTP-based
 */
export type Schema14 = Schema15 | null;

export type Schema15 = number;

/**
 * URL path of the MCP endpoint when transport is HTTP-based
 */
export type Schema16 = Schema17 | null;

export type Schema17 = string;

/**
 * HTTP health check configuration for the process
 */
export type Schema18 = Schema19;

export type Schema19 = {
    /**
     * Whether the health check is active
     */
    enabled: boolean;
    /**
     * URL that the health check polls
     */
    url?: Schema20;
    /**
     * Seconds to wait before the first health check
     */
    delaySeconds: Schema21 | null;
    /**
     * Seconds between health checks
     */
    intervalSeconds: Schema22 | null;
    /**
     * Number of consecutive failures before the process counts as unhealthy
     */
    failureThreshold: Schema23 | null;
};

export type Schema20 = string;

export type Schema21 = number;

export type Schema22 = number;

export type Schema23 = number;

/**
 * Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
 */
export type Schema24 = Schema25 | null;

export type Schema25 = {
    cpu?: Schema26;
    memory?: Schema27;
};

/**
 * CPU limit in Kubernetes quantity format (e.g. "500m" or "1")
 */
export type Schema26 = string;

/**
 * Memory limit in Kubernetes quantity format (e.g. "512Mi" or "1Gi")
 */
export type Schema27 = string;

/**
 * Resources reserved for the process: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
 */
export type Schema28 = Schema29 | null;

export type Schema29 = {
    cpu?: Schema30;
    memory?: Schema31;
};

/**
 * CPU reserved for the deployment, in Kubernetes quantity format (e.g. "250m" or "1"). This is the minimum the deployment is guaranteed when the hardware is busy; when capacity is free it may use more. Reserved capacity counts against the organization total even while the server idles, so keep it at what the server needs, not what it may burst to
 */
export type Schema30 = string;

/**
 * Memory reserved for the deployment, in Kubernetes quantity format (e.g. "384Mi" or "1Gi"). Unlike CPU this is also the hard ceiling: a process that exceeds it is terminated
 */
export type Schema31 = string;

export type Schema32 = {
    /**
     * Whether the server gets a persistent volume
     */
    enabled: boolean;
};

export type Schema33 = {
    /**
     * Whether the server joins the tailnet
     */
    enabled: boolean;
    /**
     * Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
     */
    authKey: string;
    /**
     * Machine name on the tailnet. Defaults to gatana-<server slug>
     */
    hostname?: Schema34 | null;
};

export type Schema34 = string;

/**
 * Transport type discriminator, always "sse"
 */
export type Schema35 = 'sse';

/**
 * URL of the MCP SSE endpoint
 */
export type Schema36 = string;

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema37 = Schema38;

export type Schema38 = Array<[
    string,
    string
]>;

/**
 * Transport type discriminator, always "hosted"
 */
export type Schema39 = 'hosted';

/**
 * Runtime that executes the hosted tool functions
 */
export type Schema40 = 'node24' | 'python313';

/**
 * Environment variables for the hosted runtime, as [name, value] pairs
 */
export type Schema41 = Schema42;

export type Schema42 = Array<[
    string,
    string
]>;

/**
 * Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
 */
export type Schema43 = Schema44 | null;

export type Schema44 = {
    cpu?: Schema26;
    memory?: Schema27;
};

/**
 * Resources reserved for the hosted runtime: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
 */
export type Schema45 = Schema46 | null;

export type Schema46 = {
    cpu?: Schema30;
    memory?: Schema31;
};

export type Schema47 = {
    /**
     * Whether the server gets a persistent volume
     */
    enabled: boolean;
};

export type Schema48 = {
    /**
     * Whether the server joins the tailnet
     */
    enabled: boolean;
    /**
     * Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
     */
    authKey: string;
    /**
     * Machine name on the tailnet. Defaults to gatana-<server slug>
     */
    hostname?: Schema49 | null;
};

export type Schema49 = string;

/**
 * Transport type discriminator, always "openapi"
 */
export type Schema50 = 'openapi';

/**
 * How the OpenAPI spec is supplied: from a URL or as inline content
 */
export type Schema51 = 'specUrl' | 'spec';

/**
 * URL to fetch the OpenAPI spec from, used when method is "specUrl"
 */
export type Schema52 = Schema53;

export type Schema53 = string | '';

/**
 * Inline OpenAPI spec content, used when method is "spec"
 */
export type Schema54 = Schema55;

export type Schema55 = string;

/**
 * Base URL for the API requests generated from the spec
 */
export type Schema56 = Schema57;

export type Schema57 = string | '';

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema58 = Schema59;

export type Schema59 = Array<[
    string,
    string
]>;

/**
 * Transport type to create with a default configuration, used instead of transportConfig
 */
export type Schema60 = Schema61;

export type Schema61 = 'httpstreaming' | 'sse' | 'stdio' | 'hosted' | 'openapi';

export type Schema62 = Schema63;

/**
 * Human-readable description of the server
 */
export type Schema63 = string;

export type Schema64 = Schema65;

/**
 * Authorization configuration for the server
 */
export type Schema65 = ServerAuthorization;

/**
 * Authorization method that the server uses
 */
export type Schema66 = 'none' | 'oauth' | 'oauth-client-credentials' | 'apikey';

/**
 * Whether credentials are shared for the whole server or stored per user
 */
export type Schema67 = Schema68 | Schema69;

export type Schema68 = 'server';

export type Schema69 = 'user';

/**
 * Names of the API keys that the server expects
 */
export type Schema70 = Schema71;

export type Schema71 = Array<string>;

export type Schema72 = 'server-scoped' | 'skip' | 'any';

export type Schema73 = Schema74;

/**
 * Discovered OAuth metadata, or null when not discovered
 */
export type Schema74 = Schema75 | ServerOAuthMetadata;

export type Schema75 = null;

/**
 * Discovered protected resource metadata (RFC 9728)
 */
export type Schema76 = Schema77;

export type Schema77 = {
    /**
     * Resource identifier from the protected resource metadata
     */
    id?: Schema78;
    /**
     * Scopes that the protected resource supports
     */
    availableScopes?: Schema79;
    /**
     * URL where the protected resource metadata was fetched from
     */
    metadataUrl?: Schema80;
};

export type Schema78 = string;

export type Schema79 = Array<string>;

export type Schema80 = string;

/**
 * Discovered authorization server metadata (RFC 8414)
 */
export type Schema81 = Schema82;

export type Schema82 = {
    /**
     * Issuer identifier of the authorization server
     */
    issuer?: Schema83;
    /**
     * URL of the authorization endpoint
     */
    authorizeEndpoint?: Schema84;
    /**
     * URL of the device authorization endpoint
     */
    deviceAuthorizationEndpoint?: Schema85;
    /**
     * URL of the token endpoint
     */
    tokenEndpoint?: Schema86;
    /**
     * Extra query parameters to add to the authorization request
     */
    extraAuthorizationParameters?: Schema87;
    /**
     * URL of the dynamic client registration endpoint
     */
    registrationEndpoint?: Schema88;
    /**
     * Whether the authorization server supports PKCE
     */
    supportsPKCE?: Schema89;
    /**
     * Client authentication methods that the token endpoint supports
     */
    supportedClientAuthMethods?: Schema90;
    /**
     * Whether the authorization server supports dynamic client registration
     */
    supportsDynamicClientRegistration?: Schema91;
    /**
     * Reason why dynamic client registration is not available
     */
    noDynamicClientRegistrationReason?: Schema92;
    /**
     * URL of the authorization server documentation
     */
    serviceDocumentation?: Schema93;
    /**
     * URL where the authorization server metadata was fetched from
     */
    metadataUrl?: Schema94;
    /**
     * Scopes that the authorization server supports
     */
    availableScopes?: Schema95;
};

export type Schema83 = string;

export type Schema84 = string;

export type Schema85 = string;

export type Schema86 = string;

export type Schema87 = string;

export type Schema88 = string;

export type Schema89 = boolean;

export type Schema90 = Array<string>;

export type Schema91 = boolean;

export type Schema92 = string | null;

export type Schema93 = string;

export type Schema94 = string;

export type Schema95 = Array<string>;

export type Schema96 = Schema97;

/**
 * OAuth client configuration, or null when not configured
 */
export type Schema97 = Schema98 | ServerOAuthClientConfiguration;

export type Schema98 = null;

/**
 * OAuth client ID
 */
export type Schema99 = Schema100;

export type Schema100 = string;

/**
 * OAuth client secret
 */
export type Schema101 = Schema102;

export type Schema102 = string;

/**
 * OAuth grant type used to obtain tokens
 */
export type Schema103 = OAuthGrantType;

/**
 * Client authentication method used at the token endpoint
 */
export type Schema104 = Schema105 | Schema106 | Schema107 | Schema108;

export type Schema105 = 'client_secret_basic';

export type Schema106 = 'client_secret_post';

export type Schema107 = 'none';

export type Schema108 = string;

/**
 * Space-separated OAuth scopes to request
 */
export type Schema109 = Schema110;

export type Schema110 = string;

export type Schema111 = Schema112;

/**
 * Whether the server is enabled
 */
export type Schema112 = boolean;

export type Schema113 = Schema114;

/**
 * Timeout in seconds for a single protocol request to the server
 */
export type Schema114 = number;

export type Schema115 = Schema116;

/**
 * Total timeout in seconds for a tool call, including progress notifications
 */
export type Schema116 = number;

export type Schema117 = Schema118;

/**
 * Whether a progress notification resets the protocol timeout
 */
export type Schema118 = boolean;

export type Schema119 = Schema120;

/**
 * Whether large tool outputs are compressed before they are returned to the client
 */
export type Schema120 = boolean;

export type Schema121 = Schema122;

/**
 * Whether the compression transform step is applied to tool outputs
 */
export type Schema122 = boolean;

export type Schema123 = Schema124;

/**
 * Minimum output size in bytes before compression is applied
 */
export type Schema124 = number;

export type Schema125 = Schema126;

/**
 * Firewall rules evaluated against tool calls to the server
 */
export type Schema126 = Array<Schema127>;

export type Schema127 = {
    /**
     * CEL representing the condition
     */
    condition: string;
    /**
     * Action to take when the condition matches
     */
    action: 'deny' | 'modify' | 'log';
};

export type Schema128 = Schema129;

/**
 * Who can see the server: only members or the whole organization
 */
export type Schema129 = ServerVisibility;

/**
 * Read-only; accepted and ignored
 */
export type Schema130 = Schema131;

export type Schema131 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema132 = Schema133;

export type Schema133 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema134 = Schema135;

export type Schema135 = string | null;

/**
 * Read-only; accepted and ignored
 */
export type Schema136 = Schema137;

export type Schema137 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema138 = Schema139;

export type Schema139 = string | null;

/**
 * Read-only; accepted and ignored
 */
export type Schema140 = Schema141;

export type Schema141 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema142 = Schema143;

export type Schema143 = string;

export type Schema144 = string;

/**
 * URL-friendly name of the server, unique within the tenant
 */
export type Schema145 = Schema146;

export type Schema146 = string;

export type Schema147 = Schema63;

export type Schema148 = Schema65;

/**
 * Transport configuration used to connect to the server
 */
export type Schema149 = HttpStreamingTransportConfig | StdioTransportConfig | SseTransportConfig | Schema150 | HostedTransportConfig | OpenApiTransportConfig;

export type Schema150 = {
    /**
     * Transport type discriminator, always "self"
     */
    type: 'self';
    /**
     * ID of the built-in server implementation
     */
    id: string;
};

export type Schema151 = Schema74;

export type Schema152 = Schema97;

export type Schema153 = Schema112;

export type Schema154 = Schema114;

export type Schema155 = Schema116;

export type Schema156 = Schema118;

export type Schema157 = Schema120;

export type Schema158 = Schema122;

export type Schema159 = Schema124;

export type Schema160 = Schema126;

export type Schema161 = Schema129;

/**
 * Read-only; accepted and ignored
 */
export type Schema162 = Schema163;

export type Schema163 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema164 = Schema165;

export type Schema165 = string;

/**
 * Deprecated; accepted and ignored
 */
export type Schema166 = Schema167;

export type Schema167 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema168 = Schema169;

export type Schema169 = string | null;

/**
 * Read-only; accepted and ignored
 */
export type Schema170 = Schema171;

export type Schema171 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema172 = Schema173;

export type Schema173 = string | null;

/**
 * Read-only; accepted and ignored
 */
export type Schema174 = Schema175;

export type Schema175 = string;

/**
 * Read-only; accepted and ignored
 */
export type Schema176 = Schema177;

export type Schema177 = string;

export type Schema178 = string;

export type Schema179 = unknown;

export type Schema180 = string;

export type V2ListServersResponse = {
    servers: Schema181;
};

export type V2ServerDto = {
    id: Schema182;
    slug: Schema183;
    tenantId: Schema184;
    description: Schema185;
    authorization: Schema186;
    transportConfig: Schema194;
    oauthClientConfiguration: Schema253;
    oauthMetadata: Schema267;
    visibility: Schema289;
    isEnabled: Schema290;
    lastToolRefreshAt: Schema291;
    mcpProtocolVersion: Schema293;
    mcpProtocolDetectedAt: Schema294;
    timeoutProtocol: Schema296;
    timeoutTotal: Schema297;
    resetTimeoutOnProgressNotification: Schema298;
    isOutputCompressionEnabled: Schema299;
    isOutputCompressionTransformEnabled: Schema300;
    outputCompressionThresholdBytes: Schema301;
    firewallRules: Schema302;
    createdAt: Schema304;
    updatedAt: Schema305;
};

export type CredentialDtoV2 = {
    id: Schema307;
    tenantId: Schema308;
    scope: Schema309;
    userId: Schema310;
    profileId: Schema312;
    lastUsedAt: Schema314;
    authorizedAt: Schema316;
    type: Schema317;
    createdAt: Schema318;
    updatedAt: Schema319;
    serverSlug: Schema320;
    userEmail: Schema321;
    userName: Schema323;
    profileName: Schema325;
};

export type ServerCredentialsCredential = ({
    type: 'apikey';
} & ServerCredentialsApiKeys) | ({
    type: 'oauth';
} & ServerCredentialsOauthTokens) | ({
    type: 'oauth-client-credentials';
} & ServerCredentialsOauthClientCredentials);

export type ServerCredentialsApiKeys = {
    type: Schema327;
    apikeys: Schema328;
};

export type ServerCredentialsOauthTokens = {
    type: Schema330;
    tokenSet: Schema331;
};

export type ServerCredentialsOauthClientCredentials = {
    type: Schema340;
    clientConfig?: ServerOAuthClientConfigurationClientCredentials;
    tokenSet?: Schema342;
};

/**
 * Client configuration for OAuth client credentials
 */
export type ServerOAuthClientConfigurationClientCredentials = Schema341;

export type CredentialRefreshResponse = {
    id: Schema343;
    accessTokenExpiresAt: Schema344;
};

export type PaginatedCredentialAuditLog = {
    pagination: Schema346;
    data: Schema353;
};

export type CredentialAuditLog = {
    tenantId: Schema354;
    id: Schema355;
    credentialId: Schema356;
    userId: Schema357;
    eventName: Schema359;
    details: Schema360;
    createdAt: Schema363;
    updatedAt: Schema364;
};

export type Schema181 = Array<V2ServerDto>;

/**
 * Unique ID of the server
 */
export type Schema182 = string;

/**
 * URL-friendly name of the server, unique within the tenant
 */
export type Schema183 = string;

/**
 * ID of the tenant that owns the server
 */
export type Schema184 = string;

/**
 * Human-readable description of the server
 */
export type Schema185 = string;

/**
 * Authorization configuration for the server
 */
export type Schema186 = ServerAuthorizationOutput;

/**
 * Authorization method that the server uses
 */
export type Schema187 = 'none' | 'oauth' | 'oauth-client-credentials' | 'apikey';

/**
 * Whether credentials are shared for the whole server or stored per user
 */
export type Schema188 = Schema189 | Schema190;

export type Schema189 = 'server';

export type Schema190 = 'user';

/**
 * Names of the API keys that the server expects
 */
export type Schema191 = Schema192;

export type Schema192 = Array<string>;

export type Schema193 = 'server-scoped' | 'skip' | 'any';

/**
 * Transport configuration used to connect to the server
 */
export type Schema194 = HttpStreamingTransportConfigOutput | StdioTransportConfigOutput | SseTransportConfigOutput | Schema231 | HostedTransportConfigOutput | OpenApiTransportConfigOutput;

/**
 * Transport type discriminator, always "httpstreaming"
 */
export type Schema195 = 'httpstreaming';

/**
 * URL of the MCP streamable HTTP endpoint
 */
export type Schema196 = string;

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema197 = Schema198;

export type Schema198 = Array<[
    string,
    string
]>;

/**
 * Transport type discriminator, always "stdio"
 */
export type Schema199 = 'stdio';

/**
 * Command line that starts the MCP server process
 */
export type Schema200 = string;

/**
 * Docker image that the command runs in
 */
export type Schema201 = Schema202;

export type Schema202 = string;

/**
 * Environment variables for the process, as [name, value] pairs
 */
export type Schema203 = Schema204;

export type Schema204 = Array<[
    string,
    string
]>;

/**
 * Protocol that the launched process speaks
 */
export type Schema205 = 'sse' | 'httpstreaming' | 'stdio';

/**
 * Port that the process listens on when transport is HTTP-based
 */
export type Schema206 = Schema207 | null;

export type Schema207 = number;

/**
 * URL path of the MCP endpoint when transport is HTTP-based
 */
export type Schema208 = Schema209 | null;

export type Schema209 = string;

/**
 * HTTP health check configuration for the process
 */
export type Schema210 = Schema211;

export type Schema211 = {
    /**
     * Whether the health check is active
     */
    enabled: boolean;
    /**
     * URL that the health check polls
     */
    url: Schema212;
    /**
     * Seconds to wait before the first health check
     */
    delaySeconds: Schema213 | null;
    /**
     * Seconds between health checks
     */
    intervalSeconds: Schema214 | null;
    /**
     * Number of consecutive failures before the process counts as unhealthy
     */
    failureThreshold: Schema215 | null;
};

export type Schema212 = string;

export type Schema213 = number;

export type Schema214 = number;

export type Schema215 = number;

/**
 * Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
 */
export type Schema216 = Schema217 | null;

export type Schema217 = {
    cpu?: Schema218;
    memory?: Schema219;
};

/**
 * CPU limit in Kubernetes quantity format (e.g. "500m" or "1")
 */
export type Schema218 = string;

/**
 * Memory limit in Kubernetes quantity format (e.g. "512Mi" or "1Gi")
 */
export type Schema219 = string;

/**
 * Resources reserved for the process: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
 */
export type Schema220 = Schema221 | null;

export type Schema221 = {
    cpu?: Schema222;
    memory?: Schema223;
};

/**
 * CPU reserved for the deployment, in Kubernetes quantity format (e.g. "250m" or "1"). This is the minimum the deployment is guaranteed when the hardware is busy; when capacity is free it may use more. Reserved capacity counts against the organization total even while the server idles, so keep it at what the server needs, not what it may burst to
 */
export type Schema222 = string;

/**
 * Memory reserved for the deployment, in Kubernetes quantity format (e.g. "384Mi" or "1Gi"). Unlike CPU this is also the hard ceiling: a process that exceeds it is terminated
 */
export type Schema223 = string;

export type Schema224 = {
    /**
     * Whether the server gets a persistent volume
     */
    enabled: boolean;
};

export type Schema225 = {
    /**
     * Whether the server joins the tailnet
     */
    enabled: boolean;
    /**
     * Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
     */
    authKey: string;
    /**
     * Machine name on the tailnet. Defaults to gatana-<server slug>
     */
    hostname?: Schema226 | null;
};

export type Schema226 = string;

/**
 * Transport type discriminator, always "sse"
 */
export type Schema227 = 'sse';

/**
 * URL of the MCP SSE endpoint
 */
export type Schema228 = string;

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema229 = Schema230;

export type Schema230 = Array<[
    string,
    string
]>;

export type Schema231 = {
    /**
     * Transport type discriminator, always "self"
     */
    type: 'self';
    /**
     * ID of the built-in server implementation
     */
    id: string;
};

/**
 * Transport type discriminator, always "hosted"
 */
export type Schema232 = 'hosted';

/**
 * Runtime that executes the hosted tool functions
 */
export type Schema233 = 'node24' | 'python313';

/**
 * Environment variables for the hosted runtime, as [name, value] pairs
 */
export type Schema234 = Schema235;

export type Schema235 = Array<[
    string,
    string
]>;

/**
 * Deprecated: former resource ceiling, no longer applied to deployments. Use requests to reserve capacity instead
 */
export type Schema236 = Schema237 | null;

export type Schema237 = {
    cpu?: Schema218;
    memory?: Schema219;
};

/**
 * Resources reserved for the hosted runtime: the minimum it is guaranteed when the hardware is busy. Overrides the organization default
 */
export type Schema238 = Schema239 | null;

export type Schema239 = {
    cpu?: Schema222;
    memory?: Schema223;
};

export type Schema240 = {
    /**
     * Whether the server gets a persistent volume
     */
    enabled: boolean;
};

export type Schema241 = {
    /**
     * Whether the server joins the tailnet
     */
    enabled: boolean;
    /**
     * Tailscale auth key that registers the machine. It is spent at the first registration and the machine identity is kept across restarts, so use a tagged key and do not make it ephemeral
     */
    authKey: string;
    /**
     * Machine name on the tailnet. Defaults to gatana-<server slug>
     */
    hostname?: Schema242 | null;
};

export type Schema242 = string;

/**
 * Transport type discriminator, always "openapi"
 */
export type Schema243 = 'openapi';

/**
 * How the OpenAPI spec is supplied: from a URL or as inline content
 */
export type Schema244 = 'specUrl' | 'spec';

/**
 * URL to fetch the OpenAPI spec from, used when method is "specUrl"
 */
export type Schema245 = Schema246;

export type Schema246 = string | '';

/**
 * Inline OpenAPI spec content, used when method is "spec"
 */
export type Schema247 = Schema248;

export type Schema248 = string;

/**
 * Base URL for the API requests generated from the spec
 */
export type Schema249 = Schema250;

export type Schema250 = string | '';

/**
 * Extra HTTP headers to send with each request, as [name, value] pairs
 */
export type Schema251 = Schema252;

export type Schema252 = Array<[
    string,
    string
]>;

/**
 * OAuth client configuration, or null when not configured
 */
export type Schema253 = Schema254 | ServerOAuthClientConfigurationOutput;

export type Schema254 = null;

/**
 * OAuth client ID
 */
export type Schema255 = Schema256;

export type Schema256 = string;

/**
 * OAuth client secret
 */
export type Schema257 = Schema258;

export type Schema258 = string;

/**
 * OAuth grant type used to obtain tokens
 */
export type Schema259 = OAuthGrantType;

/**
 * Client authentication method used at the token endpoint
 */
export type Schema260 = Schema261 | Schema262 | Schema263 | Schema264;

export type Schema261 = 'client_secret_basic';

export type Schema262 = 'client_secret_post';

export type Schema263 = 'none';

export type Schema264 = string;

/**
 * Space-separated OAuth scopes to request
 */
export type Schema265 = Schema266;

export type Schema266 = string;

/**
 * Discovered OAuth metadata, or null when not discovered
 */
export type Schema267 = Schema268 | ServerOAuthMetadataOutput;

export type Schema268 = null;

/**
 * Discovered protected resource metadata (RFC 9728)
 */
export type Schema269 = Schema270;

export type Schema270 = {
    /**
     * Resource identifier from the protected resource metadata
     */
    id: Schema271;
    /**
     * Scopes that the protected resource supports
     */
    availableScopes: Schema272;
    /**
     * URL where the protected resource metadata was fetched from
     */
    metadataUrl: Schema273;
};

export type Schema271 = string;

export type Schema272 = Array<string>;

export type Schema273 = string;

/**
 * Discovered authorization server metadata (RFC 8414)
 */
export type Schema274 = Schema275;

export type Schema275 = {
    /**
     * Issuer identifier of the authorization server
     */
    issuer: Schema276;
    /**
     * URL of the authorization endpoint
     */
    authorizeEndpoint: Schema277;
    /**
     * URL of the device authorization endpoint
     */
    deviceAuthorizationEndpoint: Schema278;
    /**
     * URL of the token endpoint
     */
    tokenEndpoint: Schema279;
    /**
     * Extra query parameters to add to the authorization request
     */
    extraAuthorizationParameters: Schema280;
    /**
     * URL of the dynamic client registration endpoint
     */
    registrationEndpoint?: Schema281;
    /**
     * Whether the authorization server supports PKCE
     */
    supportsPKCE: Schema282;
    /**
     * Client authentication methods that the token endpoint supports
     */
    supportedClientAuthMethods: Schema283;
    /**
     * Whether the authorization server supports dynamic client registration
     */
    supportsDynamicClientRegistration: Schema284;
    /**
     * Reason why dynamic client registration is not available
     */
    noDynamicClientRegistrationReason?: Schema285;
    /**
     * URL of the authorization server documentation
     */
    serviceDocumentation: Schema286;
    /**
     * URL where the authorization server metadata was fetched from
     */
    metadataUrl: Schema287;
    /**
     * Scopes that the authorization server supports
     */
    availableScopes: Schema288;
};

export type Schema276 = string;

export type Schema277 = string;

export type Schema278 = string;

export type Schema279 = string;

export type Schema280 = string;

export type Schema281 = string;

export type Schema282 = boolean;

export type Schema283 = Array<string>;

export type Schema284 = boolean;

export type Schema285 = string | null;

export type Schema286 = string;

export type Schema287 = string;

export type Schema288 = Array<string>;

/**
 * Who can see the server: only members or the whole organization
 */
export type Schema289 = ServerVisibility;

/**
 * Whether the server is enabled
 */
export type Schema290 = boolean;

/**
 * Time of the last tool refresh, or null if tools were never refreshed
 */
export type Schema291 = Schema292 | null;

export type Schema292 = string;

/**
 * MCP protocol version the server was last seen to speak, or empty if not yet detected
 */
export type Schema293 = string;

/**
 * Time when the protocol version was last detected, or null if never
 */
export type Schema294 = Schema295 | null;

export type Schema295 = string;

/**
 * Timeout in seconds for a single protocol request to the server
 */
export type Schema296 = number;

/**
 * Total timeout in seconds for a tool call, including progress notifications
 */
export type Schema297 = number;

/**
 * Whether a progress notification resets the protocol timeout
 */
export type Schema298 = boolean;

/**
 * Whether large tool outputs are compressed before they are returned to the client
 */
export type Schema299 = boolean;

/**
 * Whether the compression transform step is applied to tool outputs
 */
export type Schema300 = boolean;

/**
 * Minimum output size in bytes before compression is applied
 */
export type Schema301 = number;

/**
 * Firewall rules evaluated against tool calls to the server
 */
export type Schema302 = Array<Schema303>;

export type Schema303 = {
    /**
     * CEL representing the condition
     */
    condition: string;
    /**
     * Action to take when the condition matches
     */
    action: 'deny' | 'modify' | 'log';
};

/**
 * Time when the server was created
 */
export type Schema304 = string;

/**
 * Time when the server was last updated
 */
export type Schema305 = string;

export type Schema306 = {
    /**
     * Credentials the caller can read, without secret values
     */
    credentials: Array<CredentialDtoV2>;
};

/**
 * Unique ID of the credential record
 */
export type Schema307 = string;

/**
 * ID of the tenant that owns the credential
 */
export type Schema308 = string;

/**
 * Scope that the credential applies to: server, user, or profile
 */
export type Schema309 = 'server' | 'user' | 'profile';

/**
 * ID of the owning user, or null
 */
export type Schema310 = Schema311 | null;

export type Schema311 = string;

/**
 * ID of the owning profile when scope is "profile", otherwise null
 */
export type Schema312 = Schema313 | null;

export type Schema313 = string;

/**
 * Time when the credential was last used, or null if never used
 */
export type Schema314 = Schema315 | null;

export type Schema315 = string;

/**
 * Time when the credential was authorized
 */
export type Schema316 = string;

/**
 * Authorization method that the credential was created with
 */
export type Schema317 = 'oauth' | 'apikey' | 'oauth-client-credentials';

/**
 * Time when the credential record was created
 */
export type Schema318 = string;

/**
 * Time when the credential record was last updated
 */
export type Schema319 = string;

/**
 * Slug of the server that the credential authorizes access to
 */
export type Schema320 = string;

/**
 * Email address of the owning user, or null
 */
export type Schema321 = Schema322 | null;

export type Schema322 = string;

/**
 * Display name of the owning user, or null
 */
export type Schema323 = Schema324 | null;

export type Schema324 = string;

/**
 * Name of the owning profile, or null
 */
export type Schema325 = Schema326 | null;

export type Schema326 = string;

/**
 * Credential type discriminator, always "apikey"
 */
export type Schema327 = 'apikey';

/**
 * API keys as [name, value] pairs
 */
export type Schema328 = Array<Schema329>;

export type Schema329 = [
    string,
    string
];

/**
 * Credential type discriminator, always "oauth"
 */
export type Schema330 = 'oauth';

/**
 * OAuth tokens obtained from the authorization flow
 */
export type Schema331 = Schema339;

/**
 * OAuth access token
 */
export type Schema332 = string;

/**
 * Expiry time of the access token, as a Unix epoch timestamp
 */
export type Schema333 = Schema334;

export type Schema334 = number;

/**
 * OpenID Connect ID token, if the authorization server issued one
 */
export type Schema335 = Schema336;

export type Schema336 = string;

/**
 * OAuth refresh token, if the authorization server issued one
 */
export type Schema337 = Schema338;

export type Schema338 = string;

export type Schema339 = {
    accessToken: Schema332;
    accessTokenExpiresAt?: Schema333;
    idToken?: Schema335;
    refreshToken?: Schema337;
};

/**
 * Credential type discriminator, always "oauth-client-credentials"
 */
export type Schema340 = 'oauth-client-credentials';

export type Schema341 = {
    clientId: Schema255;
    clientSecret: Schema257;
    clientAuthMethod: Schema260;
    scopes: Schema265;
};

/**
 * Cached tokenset for client credentials
 */
export type Schema342 = Schema339;

/**
 * ID of the refreshed credential
 */
export type Schema343 = string;

/**
 * Expiry time of the refreshed access token, as a Unix epoch timestamp, or null if unknown
 */
export type Schema344 = Schema345 | null;

export type Schema345 = number;

/**
 * Pagination metadata
 */
export type Schema346 = {
    page: Schema347;
    limit: Schema348;
    total: Schema349;
    totalPages: Schema350;
    hasNext: Schema351;
    hasPrev: Schema352;
};

/**
 * Current page number
 */
export type Schema347 = number;

/**
 * Maximum number of items per page
 */
export type Schema348 = number;

/**
 * Total number of items across all pages
 */
export type Schema349 = number;

/**
 * Total number of pages
 */
export type Schema350 = number;

/**
 * Whether a next page exists
 */
export type Schema351 = boolean;

/**
 * Whether a previous page exists
 */
export type Schema352 = boolean;

/**
 * Items on the current page
 */
export type Schema353 = Array<CredentialAuditLog>;

/**
 * ID of the tenant that owns the entry
 */
export type Schema354 = string;

/**
 * Unique ID of the audit log entry
 */
export type Schema355 = string;

/**
 * ID of the credential that the entry belongs to
 */
export type Schema356 = string;

/**
 * ID of the user who performed the action, or null
 */
export type Schema357 = Schema358 | null;

export type Schema358 = string;

/**
 * Name of the audited event (e.g. "create", "update", "delete")
 */
export type Schema359 = string;

/**
 * Event-specific details; update events include a diff of the change
 */
export type Schema360 = {
    [key in Schema361]?: Schema362;
};

export type Schema361 = string;

export type Schema362 = unknown;

/**
 * Time when the entry was created
 */
export type Schema363 = string;

/**
 * Time when the entry was last updated
 */
export type Schema364 = string;

/**
 * Controls how tool refresh is authorized. "server-scoped" means only server-scoped credentials are required, "skip" means refresh is done without authorization, and "any" means any available credentials (server, user, profile) can be used. Defaults to "server-scoped".
 */
export type ToolRefreshCredentialPolicyOutput = Schema193;

export type ServerAuthorizationOutput = {
    method: Schema187;
    credentialsScope: Schema188;
    apikeys?: Schema191;
    toolRefreshCredentialPolicy: ToolRefreshCredentialPolicyOutput;
};

export type HttpStreamingTransportConfigOutput = {
    type: Schema195;
    url: Schema196;
    headers?: Schema197;
};

export type StdioTransportConfigOutput = {
    type: Schema199;
    command: Schema200;
    dockerImage?: Schema201;
    env?: Schema203;
    transport: Schema205;
    httpPort?: Schema206;
    urlPath?: Schema208;
    healthCheck?: Schema210;
    limits?: Schema216;
    requests?: Schema220;
    storage?: StdioTransportStorageOutput;
    tailscale?: StdioTransportTailscaleOutput;
};

/**
 * Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
 */
export type StdioTransportStorageOutput = Schema224 | null;

/**
 * Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
 */
export type StdioTransportTailscaleOutput = Schema225 | null;

export type SseTransportConfigOutput = {
    type: Schema227;
    url: Schema228;
    headers?: Schema229;
};

export type HostedTransportConfigOutput = {
    type: Schema232;
    runtime: Schema233;
    env?: Schema234;
    limits?: Schema236;
    requests?: Schema238;
    storage?: HostedTransportStorageOutput;
    tailscale?: HostedTransportTailscaleOutput;
};

/**
 * Persistent storage for the server. When enabled the server keeps one volume, mounted at the path in GATANA_DATA_DIR, which survives restarts and the idle stop. The size is fixed by the deployment and counts against the organization storage quota
 */
export type HostedTransportStorageOutput = Schema240 | null;

/**
 * Egress-only Tailscale access. When enabled the server can open connections to hosts on your tailnet, and to the subnets its routers advertise. Nothing on the tailnet can reach the server
 */
export type HostedTransportTailscaleOutput = Schema241 | null;

export type OpenApiTransportConfigOutput = {
    type: Schema243;
    method: Schema244;
    specUrl: Schema245;
    spec: Schema247;
    baseUrl: Schema249;
    headers?: Schema251;
};

export type ServerOAuthClientConfigurationOutput = {
    clientId: Schema255;
    clientSecret: Schema257;
    grantType: Schema259;
    clientAuthMethod: Schema260;
    scopes: Schema265;
};

export type ServerOAuthMetadataOutput = {
    resource?: Schema269;
    as?: Schema274;
};

export type ListServersV2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/servers';
};

export type ListServersV2Responses = {
    /**
     * Successful response
     */
    200: V2ListServersResponse;
};

export type ListServersV2Response = ListServersV2Responses[keyof ListServersV2Responses];

export type CreateServerV2Data = {
    body?: V2CreateServerRequest;
    path?: never;
    query?: never;
    url: '/servers';
};

export type CreateServerV2Responses = {
    /**
     * Successful response
     */
    200: V2ServerDto;
};

export type CreateServerV2Response = CreateServerV2Responses[keyof CreateServerV2Responses];

export type DeleteServerV2Data = {
    body?: never;
    path: {
        slug: Schema144;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type DeleteServerV2Responses = {
    /**
     * Successful response
     */
    200: unknown;
};

export type GetServerV2Data = {
    body?: never;
    path: {
        slug: Schema144;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type GetServerV2Responses = {
    /**
     * Successful response
     */
    200: V2ServerDto;
};

export type GetServerV2Response = GetServerV2Responses[keyof GetServerV2Responses];

export type PatchServerV2Data = {
    body?: V2PatchServerRequest;
    path: {
        slug: Schema144;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type PatchServerV2Responses = {
    /**
     * Successful response
     */
    200: V2ServerDto;
};

export type PatchServerV2Response = PatchServerV2Responses[keyof PatchServerV2Responses];

export type UpdateServerV2Data = {
    body?: V2UpdateServerRequest;
    path: {
        slug: Schema144;
    };
    query?: never;
    url: '/servers/{slug}';
};

export type UpdateServerV2Responses = {
    /**
     * Successful response
     */
    200: V2ServerDto;
};

export type UpdateServerV2Response = UpdateServerV2Responses[keyof UpdateServerV2Responses];

export type ListCredentialsV2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter to credentials of a single server, by server ID
         */
        serverId?: Schema180;
    };
    url: '/credentials';
};

export type ListCredentialsV2Responses = {
    /**
     * Successful response
     */
    200: Schema306;
};

export type ListCredentialsV2Response = ListCredentialsV2Responses[keyof ListCredentialsV2Responses];

export type DeleteCredentialV2Data = {
    body?: never;
    path: {
        /**
         * ID of the credential
         */
        id: string;
    };
    query?: never;
    url: '/credentials/{id}';
};

export type DeleteCredentialV2Responses = {
    /**
     * Successful response
     */
    200: Schema306;
};

export type DeleteCredentialV2Response = DeleteCredentialV2Responses[keyof DeleteCredentialV2Responses];

export type GetCredentialV2Data = {
    body?: never;
    path: {
        /**
         * ID of the credential
         */
        id: string;
    };
    query?: never;
    url: '/credentials/{id}';
};

export type GetCredentialV2Responses = {
    /**
     * Successful response
     */
    200: CredentialDtoV2;
};

export type GetCredentialV2Response = GetCredentialV2Responses[keyof GetCredentialV2Responses];

export type GetCredentialSecretV2Data = {
    body?: never;
    path: {
        /**
         * ID of the credential
         */
        id: string;
    };
    query?: never;
    url: '/credentials/{id}/secret';
};

export type GetCredentialSecretV2Responses = {
    /**
     * Successful response
     */
    200: ServerCredentialsCredential;
};

export type GetCredentialSecretV2Response = GetCredentialSecretV2Responses[keyof GetCredentialSecretV2Responses];

export type RefreshCredentialV2Data = {
    body?: never;
    path: {
        /**
         * ID of the credential
         */
        id: string;
    };
    query?: never;
    url: '/credentials/{id}/refresh';
};

export type RefreshCredentialV2Responses = {
    /**
     * Successful response
     */
    200: CredentialRefreshResponse;
};

export type RefreshCredentialV2Response = RefreshCredentialV2Responses[keyof RefreshCredentialV2Responses];

export type ListCredentialAuditLogsV2Data = {
    body?: never;
    path: {
        /**
         * ID of the credential
         */
        credentialId: string;
    };
    query?: never;
    url: '/credentials/{credentialId}/audit-logs';
};

export type ListCredentialAuditLogsV2Responses = {
    /**
     * Successful response
     */
    200: PaginatedCredentialAuditLog;
};

export type ListCredentialAuditLogsV2Response = ListCredentialAuditLogsV2Responses[keyof ListCredentialAuditLogsV2Responses];

export type GetCredentialAuditLogV2Data = {
    body?: never;
    path: {
        /**
         * ID of the credential
         */
        credentialId: string;
        /**
         * ID of the audit log entry
         */
        auditLogId: string;
    };
    query?: never;
    url: '/credentials/{credentialId}/audit-logs/{auditLogId}';
};

export type GetCredentialAuditLogV2Responses = {
    /**
     * Successful response
     */
    200: CredentialAuditLog;
};

export type GetCredentialAuditLogV2Response = GetCredentialAuditLogV2Responses[keyof GetCredentialAuditLogV2Responses];
